### ISSUE TITLE
Crash when open inventory

### ISSUE THREAD

**Issue by IzumoK** [Sildurs-shaders/sildurs-shaders.github.io#10]
As the tittle says, whenever I open my inventory while using **Sildur's Vibrant shaders v1.22 High** my game automatically crashes every single time. I've tested this in Singleplayer and multiplayer, always crashes.

I am running MC 1.14.4 with the following mods installed:
forgemod_VoxelMap-1.9.13b_for_1.14.4
Hwyla-forge-1.10.5-B66_1.14.4
jei-1.14.4-6.0.0.10
LightOverlay-3.4
preview_OptiFine_1.14.4_HD_U_F4_pre2
worldedit-forge-mc1.14.4-7.0.1

[crash-2019-08-22_18.17.18-client.txt](https://github.com/Sildurs-shaders/sildurs-shaders.github.io/files/3532149/crash-2019-08-22_18.17.18-client.txt)

**Comment by Sildurs-shaders** [comment]
Shaders usually don't crash the game, sounds like a mod issue to me. Now it might work with optifine if you don't select a shaderpack but that's only because the shadersmod is kinda inactive in that state.
