### ISSUE TITLE
Boats appear waterlogged

### ISSUE THREAD

**Issue by Shtuffs** [Sildurs-shaders/sildurs-shaders.github.io#100]
When I use a boat with shaders, the boats look waterlogged: 

![image](https://user-images.githubusercontent.com/46979803/95006406-39725f80-05d2-11eb-9696-63a66a226ff6.png)

**Comment by poppyseed0054** [comment]
I have this issue also. I'm using Sildurs Vibrant Shaders v1.281 Lite with 1.16.3 and Optifabric.

**Comment by ntroutman** [comment]
Also seeing this issue.

**Comment by Sildurs-shaders** [comment]
Fixed in the upcoming version.
