### ISSUE TITLE
[1.16.3] Clouds set to "default MC" cause whiteworld when viewed from above

### ISSUE THREAD

**Issue by RalphORama** [Sildurs-shaders/sildurs-shaders.github.io#101]
# The issue

With Sildur's Vibrant Shaders 1.281 Medium, if the option `Sky & Lighting` > `Clouds` is set to `Default MC`, clouds make the world entirely white with glitchy water textures when viewed from above.

![2020-10-08_12 15 59](https://user-images.githubusercontent.com/6566104/95485817-3d023f80-0960-11eb-85c8-0d9484b959f8.png)

# Installation info

- Minecraft 1.16.3
- Forge 34.1.0
- Mods:
   - **OptiFine 1.16.3 HD U G3**
   - AppleSkin 1.0.14
   - ClientTweaks 5.2.0
   - cloth-config 4.1.0
   - jei 7.5.0.43
   - JustEnoughResources 0.12.0.100
   - light-overlay 5.5.3
   - MouseTweaks 2.13
   - ReAuth 3.9.2
   - Xaero's Minimap 20.25.0
   - Xaero's World Map 1.11.0
- Sildur's Vibrant Shaders 1.281 Medium
   - Config: [Sildurs Vibrant Shaders v1.281 Medium.zip.txt][1]

[1]: https://github.com/Sildurs-shaders/sildurs-shaders.github.io/files/5349319/Sildurs.Vibrant.Shaders.v1.281.Medium.zip.txt

**Comment by Sildurs-shaders** [comment]
Known issue, default clouds aren't supported well in the shadersmod.
