### ISSUE TITLE
Name Tag 

### ISSUE THREAD

**Issue by SuperPawmaple** [Sildurs-shaders/sildurs-shaders.github.io#102]
I am using sildur vibrant v1.281 high on 1.16.3 with Optifine latest version. I encoutner an issue where all name tags are completely black with theres a light source or block between them. If you are close to the person or item, without a block between them, it is presented in a black border and transparent name. However, if theres a block between them, its completely black. (Liquid not included.P)

**Comment by MunchyCrunchy** [comment]
My issue is quite similar, nametags appear with a solid black background and white text. I'm using v1.281 high on 1.16.2 with the corresponding optifine.

**Comment by spinnerX49** [comment]
same

**Comment by Sildurs-shaders** [comment]
Should be fixed in upcoming update
