### ISSUE TITLE
Sandstone wet?

### ISSUE THREAD

**Issue by Linkyop** [Sildurs-shaders/sildurs-shaders.github.io#104]
1.16.3, v1.281 High-Motionblur, OF HD U G3/G4 pre2.
Sandstone blocks looks always wet for some reason.
![Wet?](https://user-images.githubusercontent.com/60701198/95690533-d8253e80-0c18-11eb-9d90-7d74057ec9ce.png)
![Wet?](https://user-images.githubusercontent.com/60701198/95690534-d9566b80-0c18-11eb-8c16-44d86dad45fe.png)

**Comment by Sildurs-shaders** [comment]
That's just the screenspace reflection which can be tweaked in the ingame shader options.
