### ISSUE TITLE
Some Recommendations 

### ISSUE THREAD

**Issue by Jettieboi** [Sildurs-shaders/sildurs-shaders.github.io#105]
This is my favorite Shader pack and I use it all the time but I have one annoyance with it. In other shader packs like Seus, I am able to change what light is emitted from a block. for example, i can make glowstone give off soft yellow light and I can make the lantern give off blue light at the same time. With your shader pack, I can only change the color of light for all light sources, not individual ones. Please tell me If it is possible to do so already with your shader pack, Sildur. also, an option to turn off or on the shaders in other dimensions would be nice.

**Comment by Sildurs-shaders** [comment]
You can only recolor the whole lightmap in minecraft, dynamic lights requires expensive raytracing which might be implemented at some point.
