### ISSUE TITLE
Version compatible with Canvas?

### ISSUE THREAD

**Issue by NatoBoram** [Sildurs-shaders/sildurs-shaders.github.io#108]
Is it possible to create a version compatible with [Canvas](https://github.com/grondag/canvas)?

**Comment by Sildurs-shaders** [comment]
Sounds like an optifine / shadersmod issue, you should ask there.

**Comment by NatoBoram** [comment]
Canvas is an entirely different "shader-based Minecraft renderer" from Optifine and there's no Canvas-based shaders yet, that's why I was asking here. I was just curious to know if you'd be interested in creating a new shaderspack for a different renderer than Optifine.

**Comment by RUSSObrz** [comment]
I must admit that I miss a nice and light shaders while playing with canvas, there is already a lumilight shaders for canvas which is well done but in relation to performance it is very deplorable.  If we could have a sildurs port for the canvas it would be a great catch.
