### ISSUE TITLE
There are some problems with the rendering of leaves in 1.281

### ISSUE THREAD

**Issue by Vang-z** [Sildurs-shaders/sildurs-shaders.github.io#109]
This is a excellent Shaders. But in version 1.281 there are something wrong with the rendering of leaves (We can see the underground world through the leaves), when I turn back to 1.27 the problem was solved. Thank you in advance for your repair.
![Snipaste_2020-11-14_21-19-09](https://user-images.githubusercontent.com/44422499/99147978-02f32e80-26c0-11eb-8218-253ecf86e005.jpg)

**Comment by Sildurs-shaders** [comment]
Should be fixed in upcoming version.
