### ISSUE TITLE
Wishlish

### ISSUE THREAD

**Issue by BenjaminHoegh** [Sildurs-shaders/sildurs-shaders.github.io#11]
First of all, this is an amazing shader, LOVE IT

Only have a few wishes
 1. Underwater like SEUS E9, the current one in this shader is really boring
 2. The Shader prevent you from seeing guidelines from the mod Litematica (schematic)
 3. Ray tracing (not a must, its just awesome)
 4. Remove wet effect from snow
 5. Option to disable/enable wet effect
 6. Remove the reflections of mobs and trees from snow

**Comment by Sildurs-shaders** [comment]
Water was reworked in v1.23 which just came out. Raytracing is already in there, used for reflections and such. Wetness should work fine unless you disable the biome check, an option to toggle it is also found in the ingame settings. Can't do much about mod issues.
