### ISSUE TITLE
AO dithered when AA is off

### ISSUE THREAD

**Issue by shawnshyguy** [Sildurs-shaders/sildurs-shaders.github.io#110]
This seems to affect 1.281, I'm not sure when the change happened, but the last-installed version I have is 1.22. I've attached screenshots to compare, screenshot with dithering is from 1.281, screenshot without is 1.22. Settings are identical across both, and both have anti-aliasing off.
Ideally, I'd like to be able to have ambient occlusion on and anti-aliasing off without a dithered effect visible.
![2020-11-16_13 30 29](https://user-images.githubusercontent.com/18062048/99293109-2d540180-2810-11eb-93f7-9e577b8e9eb0.png)
![2020-11-16_13 30 38](https://user-images.githubusercontent.com/18062048/99293113-2e852e80-2810-11eb-814e-8c13fef4a184.png)

**Comment by Sildurs-shaders** [comment]
Should be improved in newer versions.
