### ISSUE TITLE
gbuffers_skybasic causes fps drop

### ISSUE THREAD

**Issue by rentrix227** [Sildurs-shaders/sildurs-shaders.github.io#111]
At specific times
0 - 2000
12000 - 15000

there is a big drop in fps and low gpu usage
this issue only affects Vibrant Shaders

comparison without and with gbuffers_skybasic
https://vimeo.com/481859066
(deleted gbuffers_skybasic.fsh and gbuffers_skybasic.vsh from the .zip file)

GPU: 9800GTX+
Drivers: 342.01 (latest available for this gpu)
OpenGL 3.3.0

**Comment by Sildurs-shaders** [comment]
Might be a driver issue since it's such an old card.
