### ISSUE TITLE
Nether brick stairs wave like leaves/grass

### ISSUE THREAD

**Issue by hootaran** [Sildurs-shaders/sildurs-shaders.github.io#116]
Self explanatory. Haven't yet figured out which waving objects option causes this, or if this affects other stairs (though it doesn't seem to).

![2020-12-07_23 15 34](https://user-images.githubusercontent.com/55056693/101439262-29347480-38e2-11eb-84bc-674d4b475c8d.png)

**Comment by Sildurs-shaders** [comment]
Optifine / Forge issue
