### ISSUE TITLE
Non-transparent textures when using the better end mod with fabric

### ISSUE THREAD

**Issue by lonkaars** [Sildurs-shaders/sildurs-shaders.github.io#119]
When using the [BetterEnd](https://www.curseforge.com/minecraft/mc-mods/betterend) mod with these shaders, the foliage doesn't have transparency. This only happens when using Sildur's vibrant shaders:

![2020-12-28_21 53 45](https://user-images.githubusercontent.com/32883851/103281314-cf036c80-49d2-11eb-8a30-d50679c54783.png)

![2020-12-28_21 55 02](https://user-images.githubusercontent.com/32883851/103281364-e6daf080-49d2-11eb-9429-fd614d9edd1f.png)

I don't think this is an issue with the mod because the leaves appear normal without shaders, and SEUS doesn't have this issue but Sildur's looks better

**Comment by Sildurs-shaders** [comment]
Should be fixed in upcoming update
