### ISSUE TITLE
Water turns dark at certain camera angles when sunPathRotation is set to 0 at noon

### ISSUE THREAD

**Issue by coderbot16** [Sildurs-shaders/sildurs-shaders.github.io#120]
Reproduction steps:

1. Download Sildur's Vibrant Shaders v1.281 Medium
2. Set the sunPathRotation to 0 in the shader options
3. `/gamerule doDaylightCycle false`
4. `/time set noon`
5. Look around near water, it should flicker to dark at very specific camera angles

Normal-colored water:
![2020-12-29_18 36 44](https://user-images.githubusercontent.com/22420959/103326477-5f5aa500-4a05-11eb-8f5f-45b658b92914.png)

Dark water (the flicker effect):
![2020-12-29_18 36 41](https://user-images.githubusercontent.com/22420959/103326482-6a153a00-4a05-11eb-8389-b774b3a4aab9.png)

**Comment by Sildurs-shaders** [comment]
Does this still happen in version 1.283?

**Comment by coderbot16** [comment]
I have not had a chance to test it yet but I'll try to test in the next few days.

**Comment by coderbot16** [comment]
I can confirm that this issue is still present on 1.283 Medium.

**Comment by Sildurs-shaders** [comment]
I think this was fixed in newer versions, closed for now.
