### ISSUE TITLE
Realistico Texture Pack Support? (labPBR)

### ISSUE THREAD

**Issue by ThisNekoGuy** [Sildurs-shaders/sildurs-shaders.github.io#121]
I recently just got the [Realistico](https://docs.matteorizzo.com/realistico-tutorial) texture pack and they claim that their pack only works correctly with shaders that follow a "labPBR standard" and doesn't mention your shader(s) as one that works with it properly.

I wanted to ask if this can be verified "unofficially" by you? And if so, perhaps communicate this to the texture pack author?

**Comment by Sildurs-shaders** [comment]
Bump and parallax mapping should be supported, just reflections are not. Vibrant shaders applies its own reflections to certain blocks that can be tweaked ingame and more blocks can be added in block.properties.
