### ISSUE TITLE
Colour of player heads with custom skins messed up

### ISSUE THREAD

**Issue by CY-Lau** [Sildurs-shaders/sildurs-shaders.github.io#123]
The colour of player heads messed up as shown in this photo. 
![image](https://user-images.githubusercontent.com/68762575/105028832-82b8c300-5a8c-11eb-83c2-79754815de15.png)
Setting: Sildurs Vibrant Shaders v1.282 Extreme-VL
Adaptive_sharpening=true
Clouds=1
defskybox=true
Depth_of_Field=true
DoF_Strength=200
emissive_R=1.1
Godrays=true
Godrays_Density=9.2
Lens_Flares=true
Lens_Flares_Strength=64.0
MB_strength=0.020
Moonlight=0.009
Motionblur=true
polishedRefl=true
POM_DIST=24.0
POM_RES=256
raytracedShadows=true
uFogDensity=200.0
waterheight=2.0
wFogDensity=50.0

**Comment by CY-Lau** [comment]
Here's one more photo which the head is placed in a darker place. 
![image](https://user-images.githubusercontent.com/68762575/105029582-7d0fad00-5a8d-11eb-9364-a826dd954252.png)

**Comment by Sildurs-shaders** [comment]
Might be fixed in the new update (v1.283)
