### ISSUE TITLE
Entity hurt / damage flash does not work on v1.283

### ISSUE THREAD

**Issue by coderbot16** [Sildurs-shaders/sildurs-shaders.github.io#125]
Tested with OptiFine 1.16.5_HD_U_G6 and Sildur's Vibrant Shaders v1.283 Medium as well as Extreme VL.

This appears to be caused by the removal of gbuffers_entities in favor of using gbuffers_textured. With that change, the entityColor uniform is no longer used, which holds both the red hurt flash when mobs are hurt as well as the white flashes of primed TNT.

Also, I noticed that you are reading the lightmap in gbuffers_textured. Technically, the lightmap is only guaranteed to be used with gbuffers_textured_lit. While this doesn't appear to cause problems right now, it's something that's good to be aware of.

**Comment by Sildurs-shaders** [comment]
Fixed in upcoming release.
