### ISSUE TITLE
Doing wierd things to texture transparency

### ISSUE THREAD

**Issue by sekelsta** [Sildurs-shaders/sildurs-shaders.github.io#127]
![2021-01-24_12 02 30](https://user-images.githubusercontent.com/19580483/105637680-a38e6900-5e3c-11eb-9784-ad8cec52c18f.png)

The cow is from Genetic Animals and the horse is from Realistic Horse Genetics, both mods that create textures for mobs at runtime by combining other textures. It looks like areas of partial transparency on the top texture are making the whole combination translucent, even where the bottom texture was opaque?

Installed:
Sildur's Vibrant shaders v1.283 High
OptiFine 1.16.4 HD U G6 
Forge 1.16.4 35.1.0
Realistic Horse Genetics 1.16.4-1.5.2
Genetic Animals 0_6_5

**Comment by Sildurs-shaders** [comment]
The texture format is probably set to translucent which causes this, you would have to change the texture property.

**Comment by sekelsta** [comment]
Do you mean like in [#24](https://github.com/Sildurs-shaders/sildurs-shaders.github.io/issues/24)? My mod doesn't specifically set any texture properties like that. In fact, I've never seen that before. If it were changed, would the alpha channel still load properly?

**Comment by Sildurs-shaders** [comment]
Does it happen on v1.27? If not it should be fixed in the upcoming release.

**Comment by sekelsta** [comment]
It doesn't happen on 1.27. Good to hear!
