### ISSUE TITLE
Weird chest transparency glitch

### ISSUE THREAD

**Issue by dessaes** [Sildurs-shaders/sildurs-shaders.github.io#128]
The glitch only happens when I use the any of sildur's shaders. I can see players and animals through the chest. When I disable the shaders, its normal but when I enable the shaders the see through glitch happen

Edit: the game is running on 1.16.5 with fabric

without shaders:
![image](https://user-images.githubusercontent.com/77950595/105660813-ba56af00-5e80-11eb-8eb7-202288900386.png)

with shaders:
![image](https://user-images.githubusercontent.com/77950595/105660636-4e744680-5e80-11eb-9296-900c8535459a.png)

My pc specs are: 

I7-8700

Gtx 980 ti

24gb of Ram

1tb WD hard drive

**Comment by Sildurs-shaders** [comment]
Fixed in latest update, grab the latest version, v1.283 from my website.
