### ISSUE TITLE
Downloads page redirecting to fishy websites

### ISSUE THREAD

**Issue by atyshka** [Sildurs-shaders/sildurs-shaders.github.io#13]
Hi, I'm super excited to try out your shaders but your downloads page is redirecting me to sketchy websites. After about 20 redirects I landed on a page that had a phony "adobe flash update" popup that was obviously a ploy to install malware. Then after further redirects I closed the page to protect myself. Is there any way I can download without using these suspicious websites? Would you consider something safer like a dropbox maybe? Thanks!

**Comment by Sildurs-shaders** [comment]
All you have to do is wait 5 seconds and press on the skip ad button, that should redirect you to mediafire, which is the host of my shaderpacks.
