### ISSUE TITLE
weird-glith-w/-mekanism

### ISSUE THREAD

**Issue by funky-monkey123** [Sildurs-shaders/sildurs-shaders.github.io#130]
I have tried to fix this but when I use this shader the bins items appear black and shaky how do I fix it?
![2021-01-26_16 20 04](https://user-images.githubusercontent.com/78054942/105919942-1b56c200-5ffc-11eb-9fd0-8d91cdbad95e.png)

**Comment by Sildurs-shaders** [comment]
Make sure to use v1.283 and keep optifine up to date.

**Comment by Sildurs-shaders** [comment]
Should be fixed in upcoming release.
