### ISSUE TITLE
Round sun reflection when default skybox is turned on.

### ISSUE THREAD

**Issue by Victorietti** [Sildurs-shaders/sildurs-shaders.github.io#132]
When I turn on default skybox to enable default square sun and moon, water reflections still show round sun and moon.
![2021-02-03_13 45 02](https://user-images.githubusercontent.com/25888307/106748897-2924cc80-6626-11eb-813f-a3eb2b8d97df.png)

**Comment by Sildurs-shaders** [comment]
Because it's still better to have this instead of nothing.
