### ISSUE TITLE
[1.16.5 / v2.283] Lighting doesn't load when first dimension one loads into isn't the Overworld

### ISSUE THREAD

**Issue by distributivgesetz** [Sildurs-shaders/sildurs-shaders.github.io#133]
### **Expected:**
When loading into a world right after starting the game, regardless of the dimension the player loads into, the lighting should load normally.

### **Current:**
When first starting the game and entering a world, if the dimension you load into isn't the Overworld, for example the Nether or The End, lighting will be non-existent.

### **Steps to reproduce:**
0. Start a creative world, build a Nether portal and go into the nether.
1. Restart the game.
2. Join back into the world.
3. To fix the issue, load the Overworld by going through a portal or by joining into another world at least once. Lighting should load normally again if you enter the Nether or The End.

### **Specs:**
Minecraft version 1.16.5
Optifine HD U G6
Sildurs Vibrant Shaders v1.283 (no settings changed)

GeForce GTX 1660
NVIDIA Game Ready Driver 461.40
(8x AMD Ryzen 5 2400G)

**Comment by Sildurs-shaders** [comment]
Optifine bug, report it to the optifine github instead.
