### ISSUE TITLE
Damage Flash not working on Java Vibrant shaders

### ISSUE THREAD

**Issue by victorvansande** [Sildurs-shaders/sildurs-shaders.github.io#136]
I've tried a bunch of different shader variations, settings, combinations, ... but the damage flash doesn't work in the latest version of the Vibrant Shaders. It's a shame, because I loved the soft red glow when hitting a mob. Would love to see this fixed.

**Comment by victorvansande** [comment]
Same thing with lightning (as in when it thunders), there's something off with the colours, lightning doesn't look white, it just looks slightly opaque. Seems to be the same with the Ender Dragon effect when it's dying (everything that has to do with rays/light effects)
![2021-02-19_00 16 11](https://user-images.githubusercontent.com/18234868/108446281-2947dd80-725e-11eb-9ab8-ae01aa77437f.png)

**Comment by Diaso0** [comment]
I'm having the same issue

**Comment by Sildurs-shaders** [comment]
Should be fixed in upcoming release.
