### ISSUE TITLE
Smooth lighting on (white) blocks

### ISSUE THREAD

**Issue by victorvansande** [Sildurs-shaders/sildurs-shaders.github.io#137]
I don't know if this is something that can be fixed, but I'd love to see a smoother transition of lighter - darker lit blocks. It really breaks the experience to see weird effects like the one on the attached image. 

Don't know if this is a shader problem or a global Minecraft issue, but it's one of the few things that really breaks the immersion in my opinion, and it would be awesome to see this resolved.

![2021-02-17_14 38 40](https://user-images.githubusercontent.com/18234868/108212364-11713c00-712e-11eb-95c2-261e18c8b8ca.png)

**Comment by Sildurs-shaders** [comment]
Issue caused by minecraft lightmap system, not much can be done about it.
