### ISSUE TITLE
[Bug] [1.16.5] [Vibrant Shaders 1.283 High] Mob Textures Transparent or Invisible

### ISSUE THREAD

**Issue by NoMoreStars** [Sildurs-shaders/sildurs-shaders.github.io#138]
**Bug: Textures on some mobs appear transparent or invisible either partially or completely. Mobs effected include Villagers, Zombie Villagers, Skeletons, Bees, and some non-vanilla mobs such as mobs from the Resourceful Bees mod.**

Villager with partially invisible textures (as well as white glitched texture)
![2021-02-18_09 07 45](https://user-images.githubusercontent.com/38673759/108388936-c3634380-71d4-11eb-8cdd-e5615d8098f2.png)

Villager with fully invisible texture (only visible when noticing belt trinket & TheOneProbe)
![2021-02-18_09 13 25](https://user-images.githubusercontent.com/38673759/108389059-e857b680-71d4-11eb-81cb-9e162c9d9476.png)

Version: Sildurs Vibrant Shaders 1.283 High
Optifine 1.6.5_HD_U_G7_pre10
Forge 36.0.22
[All the Mods 6 1.5.2](https://www.curseforge.com/minecraft/modpacks/all-the-mods-6/files/3199643)

**Comment by Sildurs-shaders** [comment]
Should be fixed in upcoming release if it doesn't happen on v1.27.
