### ISSUE TITLE
Lightning Color Issue

### ISSUE THREAD

**Issue by NoahSanders1997** [Sildurs-shaders/sildurs-shaders.github.io#14]
Lightning has the wrong color in-game
the testing I did with the screenshots included above suggest some issue with the lightning sharing colors with emissive light

I tried to find my own fix and the only relevant information I found came from this post
first commenting that lightning was invisible then finding it was rendered black
https://github.com/sp614x/optifine/issues/2383

_"Shading should be disabled for lightning texture , but those flashs of light should affect the lighting and shading of surrounding blocks"_

![2019-09-06_01 23 55](https://user-images.githubusercontent.com/17556935/64408889-11b66e00-d045-11e9-8a5c-4d8cb1f1c56e.png)

![2019-09-06_01 25 23](https://user-images.githubusercontent.com/17556935/64409006-49bdb100-d045-11e9-81ca-8b95d8ffd3df.png)

![2019-09-05_01 42 34](https://user-images.githubusercontent.com/17556935/64408328-ac15b200-d043-11e9-9475-7b0b6fd723eb.png)

![2019-09-06_01 30 31](https://user-images.githubusercontent.com/17556935/64409378-0152c300-d046-11e9-8c78-de07d1231149.png)

My specs from Minecraft's internal debug menu
![2019-09-06_01 37 58](https://user-images.githubusercontent.com/17556935/64409874-fea49d80-d046-11e9-86f3-aa9425ff847a.png)

**Comment by Sildurs-shaders** [comment]
Fixed in upcoming version, v1.26.
