### ISSUE TITLE
Mekanism Enhanced Night Vision has no impact with 'normal' shaders turned on

### ISSUE THREAD

**Issue by Aronnaxx** [Sildurs-shaders/sildurs-shaders.github.io#141]
Mekanism version: 10.0.0

Sildur's Version(s): 

Sildur's Vibrant shaders v1.283 Extreme-Volumetric lighting 

Sildur's Vibrant shaders v1.283 Extreme

Sildur's Vibrant shaders v1.283 Lite

Issue was **NOT** present on Enhanced Default, version "Sildur's Enhanced Default v1.12" , so it may have something to do with how the texture maps are handled?

Issue was submitted to Mekanism who stated they do not simply use the Night Vision potion effect (linked below)

https://github.com/mekanism/Mekanism/issues/7029

**Comment by Sildurs-shaders** [comment]
Can't be fixed since vibrant shaders uses custom fog and enhanced default uses vanilla.
