### ISSUE TITLE
Weird bug rendering the End [Enigmatica 6] [Sildur's Vibrant Medium v1.283]

### ISSUE THREAD

**Issue by Aiva418** [Sildurs-shaders/sildurs-shaders.github.io#142]
I've been playing Enigmatica 6 (v0.4.2) with the vibrant medium shaders without many issues up until now. I turned off Astral Sorcery's skybox and things have been going smoothly, even in the Nether.
The End is a different story. I honestly don't know how to describe what I'm seeing concisely enough to fit into the title of this report, let alone a Google search.
![what](https://user-images.githubusercontent.com/44123286/110883216-bc49c580-82a8-11eb-8351-548f6723b39f.png)

From what I can tell, at least 3 things are going wrong.
1. Alpha channels not being recognized, instead inverting the colors behind them.
2. Backside of blocks are rendered on top of the sides the player is looking at.
3. Some other weird nonsense messing with the hue and saturation of block textures.

Entities and water reflections seem to be rendering perfectly. It's just the blocks having problems, as far as I can tell.
In addition to the mods added by Enigmatica 6 v0.4.2, I have DynamicSurroundings-1.16.4-4.0.3.12, preview_OptiFine_1.16.5_HD_U_G8_pre1, dungeons_gear-1.16.4-3.0.6, and dungeons_mobs-1.16.4-1.0.3.
Also, this information may be relevant:
![image](https://user-images.githubusercontent.com/44123286/110884161-3e86b980-82aa-11eb-89a8-133be0068aa7.png)

**Comment by Sildurs-shaders** [comment]
Might be fixed in upcoming release.
