### ISSUE TITLE
[1.16.5] [v1.283]Campfire smoke renders below at least water and nether portal material

### ISSUE THREAD

**Issue by EcoMaster21** [Sildurs-shaders/sildurs-shaders.github.io#143]
These screenshots are both taken with OptiFine HD U G7, and Sildur's Vibrant Shaders - Extreme-Volumetric lighting with identical settings. All versions of Vibrant Shaders are affected. Enhanced Default Shaders renders correctly. Note the nether portal in the distance towards the top center.

v1.281
![2021-03-13_04 11 14](https://user-images.githubusercontent.com/26373008/111026853-58abbf00-83b2-11eb-9903-770274523928.png)
v1.283
![2021-03-13_04 11 05](https://user-images.githubusercontent.com/26373008/111026861-5c3f4600-83b2-11eb-8282-dce65d7a69a6.png)

**Comment by Sildurs-shaders** [comment]
Should be fixed in upcoming release.
