### ISSUE TITLE
[Enhanced Default] [Sildurs Vibrant] Custom biome colormap lava not working

### ISSUE THREAD

**Issue by ButterSpreadBread720** [Sildurs-shaders/sildurs-shaders.github.io#145]
Lava colormap doesn't work in Sildur's shaders.

Sildurs Enhanced default v1.12:

![2021-04-06_19 31 49](https://user-images.githubusercontent.com/76714781/113803088-b19c1800-9710-11eb-84f1-58c5202936fa.png)

Internal:

![2021-04-06_19 32 27](https://user-images.githubusercontent.com/76714781/113803173-d6908b00-9710-11eb-825e-ddfe6003562c.png)

Sildurs Vibrant:

![2021-04-06_19 53 47](https://user-images.githubusercontent.com/76714781/113803740-f8d6d880-9711-11eb-9267-311717c7307b.png)

I have tested other shaders, and so far this only happens to Sildurs.

**Comment by Answordy** [comment]
Same for me.

**Comment by Sildurs-shaders** [comment]
Which optifine version? Does it happen 1.16+ too?

**Comment by Sildurs-shaders** [comment]
Might be fixed in upcoming version. If possible link me a resourcepack with a custom lava color map for debugging.

**Comment by Sildurs-shaders** [comment]
Should be fixed in v1.30
