### ISSUE TITLE
[MacOS] Turning off shadows breaks water

### ISSUE THREAD

**Issue by doubledammit** [Sildurs-shaders/sildurs-shaders.github.io#146]
Turning shadows off breaks the water shader. This happens in 1.29 as well as the 1.28x versions (and possibly before that but I haven't tested).

2019 27" iMac w/ Radeon Pro 580X 8GB.

I'd give you a line number for the error if I knew how to do so. Hell, I'd hack in my own workaround if I could figure out where this was actually happening. (Believe me, I've tried)

I love your shaders but I also love a high frame rate and shadows are the easiest way to hamper the latter. (And yeah, I could set them to 'lowest' but then they look like shit and still require a rendering pass. I'd rather disable them)
![2021-05-07_03 06 39](https://user-images.githubusercontent.com/83812628/117427434-45b0f900-aee2-11eb-80b0-344aee11db25.png)

**Comment by doubledammit** [comment]
A few more details about why this matters to me: I play a lot of CTMs (Complete the Monument), the majority of which take place in underground spaces. With such a map, shadows are entirely wasted, but I can't turn them off without also destroying water (all water, including underground water).

**Comment by Sildurs-shaders** [comment]
I need ur latest log from .minecraft/logs after loading the shaders and getting the error message in chat.

**Comment by Sildurs-shaders** [comment]
Sorry for the late response, this is fixed in the upcoming release.
