### ISSUE TITLE
Sildur's shaders 1.28.2+ reflections

### ISSUE THREAD

**Issue by Jaozim-123** [Sildurs-shaders/sildurs-shaders.github.io#148]
I'm having some issues with the glass reflections on sildur's shaders 1.282+
This is 1.29
![image](https://user-images.githubusercontent.com/84182391/119854778-be0a4900-bee7-11eb-8e54-12b69b4fb148.png)
This is 1.28.1
![image](https://user-images.githubusercontent.com/84182391/119854938-e2febc00-bee7-11eb-98bf-2ac303dad1df.png)

**Comment by Sildurs-shaders** [comment]
Reflections became less accurate to speed up performance.
