### ISSUE TITLE
Animated texture glitch? 1.29

### ISSUE THREAD

**Issue by Answordy** [Sildurs-shaders/sildurs-shaders.github.io#149]
I have honestly zero clue what is this and how is this related to shaders (if it is related at all, if it isn't.. sorry for bothering), but I have very minor knowledge on the topic. 
All i know is on these pictures below. I have this long animated texture, very bad quality, but it works. Except with Sildurs 1.29 Shader. There is some kind of visual issue, corruption going on in the animation. 
The two pictures has the same content, same item, same textures, same shader settings (tried messing around with them and resetting it, no change) ect. The only difference is the shader. 

On the first one we have Sildurs Extreme + VL - 1.283. We have no issues here. 
![1 283](https://user-images.githubusercontent.com/82783515/120410103-a3eec180-c352-11eb-8fa7-5ffa173afc84.gif)

On the second one we have Sildurs Extreme + VL - 1.29. We can see this strange grainy visual noise here.
![1 29](https://user-images.githubusercontent.com/82783515/120409919-4195c100-c352-11eb-8706-40135aaa2fe3.gif)

It's not a noticable problem and very hard to recreate, I actually has this problem only on this item I guess. It isn't necessary a shader side problem, but I don't know. I just leave it here.

**Comment by Sildurs-shaders** [comment]
Closed for now, reopen if issue still persists.
