### ISSUE TITLE
TFC compatability

### ISSUE THREAD

**Issue by aldo1028** [Sildurs-shaders/sildurs-shaders.github.io#15]
Hello, was wondering if you could look into making this shader pack work with TFC. It remakes all of Vanilla worldgen and blocks, oceans and sky. https://github.com/TerraFirmaCraft/TerraFirmaCraft
See screenshots below:

With your new Default Shader

![2019-09-07_01 28 23](https://user-images.githubusercontent.com/1907447/64470293-19424980-d10f-11e9-83bc-96b36e439604.png)
![2019-09-07_01 28 27](https://user-images.githubusercontent.com/1907447/64470295-1e06fd80-d10f-11e9-8b47-dddadf849f0f.png)
![2019-09-07_01 28 40](https://user-images.githubusercontent.com/1907447/64470296-20695780-d10f-11e9-9b8d-e5d4cf551654.png)
![2019-09-07_01 29 05](https://user-images.githubusercontent.com/1907447/64470298-23644800-d10f-11e9-95b4-002806215932.png)

With Vibrant Shader, taking at same time of day

![2019-09-07_01 29 22](https://user-images.githubusercontent.com/1907447/64470306-3c6cf900-d10f-11e9-9715-1092624e5d50.png)
![2019-09-07_01 29 30](https://user-images.githubusercontent.com/1907447/64470308-40991680-d10f-11e9-99de-06d5c5b7a460.png)

**Comment by Sildurs-shaders** [comment]
If even enhanced default doesn't work there's not much I can do about it. This mod seems to interfere to much with the shadersmod.
