### ISSUE TITLE
No Shadows on Item Models (Vibrant Shaders 1.28+)

### ISSUE THREAD

**Issue by alfred567** [Sildurs-shaders/sildurs-shaders.github.io#150]
![2021-06-02_17 40 25](https://user-images.githubusercontent.com/61970761/120430523-4054aa80-c3cb-11eb-91ae-6a452ba1f9c7.png)
![2021-06-02_17 41 05](https://user-images.githubusercontent.com/61970761/120430529-421e6e00-c3cb-11eb-81a5-c4e4c2ca68ed.png)
Since version 1.28, shadows on custom item models are no longer working. These images show .JSON item models from a resource pack placed on item frames. Previously, shadows could be enable by turning on ambient occlusion in options: shading. Now, even after toggling every possible setting, the shadows are not rendering. # #

**Comment by Sildurs-shaders** [comment]
They way things are rendered was rewritten many times to fix certain issues, so currently AO is not applied to the entity itself. Might be fixed in the upcoming update.
