### ISSUE TITLE
Some objects are too bright depending on camera angle

### ISSUE THREAD

**Issue by gab8** [Sildurs-shaders/sildurs-shaders.github.io#153]
For example:
![2021-06-12_11 06 12](https://user-images.githubusercontent.com/38043728/121778663-463a5080-cb6e-11eb-8119-34f040472401.png)

But if I tilt it a bit:

![2021-06-12_11 06 17](https://user-images.githubusercontent.com/38043728/121778671-4fc3b880-cb6e-11eb-994c-2ac2e31c5210.png)

Seen it with Beds and chests so far. Shader is 1.29 extreme VL

Thanks

**Comment by gab8** [comment]
Also, this is with the Valhelsia 3 pack, not sure if that matters.

**Comment by Sildurs-shaders** [comment]
Does this happen on 1.16+ too? If not it's an optifine bug and should be reported to the optifine github instead.
