### ISSUE TITLE
Sildurs Vibrant Shaders Medium 1.29: shaders crash in Nether when disabling TAA

### ISSUE THREAD

**Issue by Neeqstock** [Sildurs-shaders/sildurs-shaders.github.io#154]
Shaders crash (using Medium version) when TAA is disabled in Nether, resulting in a black world and an error.
Game version: 1.16.5

Tried with both Optifine 1.16.5 HD U G8 (last version this moment)
and Sodium + Iris 0.11.3 1.16.5 (by tweaking shaders.settings, since there's no shaders options menu)

In Optifine, console says:
_OpenGL Error: 1282 (Invalid operation)
[Shaders] Error: Invalid program "composite"_

I already tried to disable any resource pack (then using Vanilla), but the problem persists.
Already tried also to clean reinstall the shader.

**Comment by Sildurs-shaders** [comment]
Fixed in upcoming version.
