### ISSUE TITLE
Tinted glass + water issues

### ISSUE THREAD

**Issue by meza** [Sildurs-shaders/sildurs-shaders.github.io#155]
Tinted glass breaks the way the water is rendered and it doesn't show up in water reflections either.

![huge_2021-07-05_10 35 20](https://user-images.githubusercontent.com/211977/124451165-05a0b200-dd7d-11eb-91ff-c2de0593e13e.png)

![huge_2021-07-05_10 36 58](https://user-images.githubusercontent.com/211977/124451157-03d6ee80-dd7d-11eb-92e0-a4ef0e41764a.png)

**Comment by Sildurs-shaders** [comment]
That's a known issue, this shaderpack is old and this is how it used to be back then, there were many issues with rendering through transparency. Will be fixed in a potential rewrite of vibrant shaders but probably not in an update.
