### ISSUE TITLE
Sky goes black at certain angles during sunset/moonrise

### ISSUE THREAD

**Issue by caustic98** [Sildurs-shaders/sildurs-shaders.github.io#156]
The sky goes black/nothing rendered when sun is setting on latest version when the sun is setting and when the moon is beginning to rise. Tried disabling volumetric lighting/clouds, godrays, sky blur, original skybox but makes no difference. Issue isn't present in version 1.283

![2021-07-10_21 51 24](https://user-images.githubusercontent.com/87246408/125176148-1b710580-e1c9-11eb-9698-5877cf55ebd1.png)

**Comment by Ari-RERA-43** [comment]
If you are on 1.17.x, try updating to OptiFine 1.17.1 pre27.

**Comment by tsumeone** [comment]
This is still a problem on 1.17.1 pre29

**Comment by Sea-Kerman** [comment]
Can confirm this still happens

**Comment by Sildurs-shaders** [comment]
If it does not happen on v1.16+ it's an optifine bug and should be reported to the optifine github.

**Comment by Sildurs-shaders** [comment]
Bug introduced by optifine in 1.17+ fixed in upcoming version though.
