### ISSUE TITLE
Enchantment glints have z-fighting in the nether and end

### ISSUE THREAD

**Issue by coderbot16** [Sildurs-shaders/sildurs-shaders.github.io#158]
`gbuffers_armor_glint` uses a series of matrix multiplications, but `gbuffers_textured` uses ftransform. The matrix multiplications introduce precision errors compared to ftransform that cause the vertex depths to be subtly different, which is enough to cause issues with the glint effect. The glint must have the exact same transformations as the content it's being applied to in order to work properly, otherwise issues like this show up.

Reccomended fix: Replace the content of lines 27-29 of gbuffers_armor_glint.vsh with `gl_Position = ftransform();`

Notably, the overworld is not affected by this issue, only the nether and end. It seems like this is because the nether and end copy code from the overworld, but aren't updated in sync with the overworld, introducing discrepancies like this. If possible, I'd recommend using the `#include` system to share code between dimensions to avoid issues like this in the future.

![Enchantment glint z-fighting in the nether and end](https://user-images.githubusercontent.com/22420959/112559640-a51dd400-8d8e-11eb-87f4-9df1054f479d.png)

**Comment by coderbot16** [comment]
To clarify: This has been observed on Sildur's Vibrant Shaders Lite v1.29, but likely happens on other profiles of the pack too.

**Comment by Sildurs-shaders** [comment]
Fixed in upcoming version.
