### ISSUE TITLE
Sildurs shaders not working Optifine 1.17.1 Pre 30 MacOS

### ISSUE THREAD

**Issue by BenMerino** [Sildurs-shaders/sildurs-shaders.github.io#159]
I've downloaded the latest Optifine which finally fixed shaders for MacOS, but when I try to load it I can only see a black screen with the error message:

No EXT_framerbuffer_object
[Shaders] Error: invalid program "composite1"
![Uploading Screen Shot 2021-07-21 at 16.36.52.png…]()

**Comment by Sildurs-shaders** [comment]
I need ur latest.log in .minecraft/logs to take a look at this.
