### ISSUE TITLE
[Request] Light colors per block

### ISSUE THREAD

**Issue by MisterQuiggly** [Sildurs-shaders/sildurs-shaders.github.io#16]
Like the title suggests, I think if we could choose the color of lighting per block it would be really helpful and look much better.
By default, the light coming from illuminating blocks or items is orangeish. This works well for some blocks, but for items like Sea Lanterns it doesn't. It would be nice if I could manually choose the light color for sea lantern, and make it like white or light blue. It'd look much better.

**Comment by MisterQuiggly** [comment]
https://imgur.com/a/zfaLgt1
First screenshot is how it normally is, the others are how it could be.

**Comment by Sildurs-shaders** [comment]
Lighting per block cannot be done unless you raytrace it. What most shaderpacks do is modify the lightmap, so they can only change the color of every emissive block.
