### ISSUE TITLE
the sky turns black  sometime

### ISSUE THREAD

**Issue by JianlingRemix** [Sildurs-shaders/sildurs-shaders.github.io#160]
![mmexport1627468688087](https://user-images.githubusercontent.com/53504770/127312224-4d8ac2f6-d28d-4614-ac69-5561ed403d31.jpg)
![mmexport1627468690192](https://user-images.githubusercontent.com/53504770/127312231-3f88bfac-af9a-4aa4-9e4a-81d6dd3b85e9.jpg)
sometimes it'll happen in 1.17.1,pls fix it.

**Comment by JianlingRemix** [comment]
I've already updated my optifine hs to pre30,and the problem still exists

**Comment by Sildurs-shaders** [comment]
See https://github.com/Sildurs-shaders/sildurs-shaders.github.io/issues/156
