### ISSUE TITLE
Enhanced Default breaks the recoil animation of Vic's Modern Warfare

### ISSUE THREAD

**Issue by MrRedstoneA1** [Sildurs-shaders/sildurs-shaders.github.io#163]
As the title says, the shaders break the recoil animation when firing a gun from the mod. Equip any gun, pistols are easiest to see the effect, fire the gun. The recoil animation doesn't play. I managed to find out which files cause the animation to break: gbuffers_texture.fsh and gbuffers_texture.vsh
Deleting those files lets the recoil animation play but it also breaks waving objects and shadows.

**Comment by Sildurs-shaders** [comment]
Mod support with shaders is very tricky. Enhanced default renders the game as close as possible to the vanilla way.
