### ISSUE TITLE
Night vision effect from coduit power not working

### ISSUE THREAD

**Issue by amenbr1** [Sildurs-shaders/sildurs-shaders.github.io#164]
The night vision effect of the conduit power buff is not working. Everything is dark. Effects v1.29 Vibrant Shaders.

To replicate:
Place and activate a conduit underwater.

Expected result:
Night vision is given (similar to drinking a potion).

Actual result:
Everything stays dark as if you don't have night vision.

**Comment by Sildurs-shaders** [comment]
Works in enhanced default, in vibrant shaders only at night.

**Comment by Sildurs-shaders** [comment]
Should be fixed in upcoming version.
