### ISSUE TITLE
Enhanced Default Shulker Box Underwater

### ISSUE THREAD

**Issue by amenbr1** [Sildurs-shaders/sildurs-shaders.github.io#168]
Using Enhanced default the sides of shulker boxes placed underwater are given the falling water texture and not the texture of a shulker box. The top and bottom both have the correct texture. The side textures are effected by the waves animation.
This also affects shulker boxes placed in 1 deep water.

The expected result is the same as when using vibrant:
Shulker texture is displayed on all sides.

**Comment by Sildurs-shaders** [comment]
Enhanced Default renders most parts like default minecraft does, this also occurs in default minecraft. So up to mojang to change or keep, if they designed it like that.
