### ISSUE TITLE
Enhanced Default Enchanted Items Underwater Are Sometimes White

### ISSUE THREAD

**Issue by amenbr1** [Sildurs-shaders/sildurs-shaders.github.io#169]
(Enhanced Default)
Sometimes when holding an enchanted item while underwater it will display as fully white.
This occurs when more than a few blocks underwater and is most commonly caused by sunlight.
The sections of the item that are in shadow (such as the players shadow) will display correctly, while the sections of the item that are not in shadow will display as white.

Can be reproduced by standing behind kelp and looking at the sun when more than a few blocks underwater.

After looking into it a bit more:
When above water or only a few blocks underwater shadows are shown if you look down at the sea-grass / kelp.
As you descend into the water the shadows go away. This is where you run into the bug.

I have found this also occurs (though less frequently) when near a vertical water stream and light sources.

**Comment by Sildurs-shaders** [comment]
I think this is an optifine bug, so closed for now.
