### ISSUE TITLE
Wierd cloud issu

### ISSUE THREAD

**Issue by drago87** [Sildurs-shaders/sildurs-shaders.github.io#17]
Half the screen not showing the clouds.
There is a clear dividing line in the middle.
It is the same when it's not raining.
Using Sildurs Vibrant Shaders v1.23 High
![shader](https://user-images.githubusercontent.com/6805712/64720240-448bb680-d4ca-11e9-8268-f11876298a28.png)

**Comment by Sildurs-shaders** [comment]
Caused by astral sorcery, you must disable it's custom sky stuff.
