### ISSUE TITLE
More dynamic slow auto-exposure

### ISSUE THREAD

**Issue by istvanmate** [Sildurs-shaders/sildurs-shaders.github.io#175]
I tried the shader with Iris, and have to say, it works awesome. Is there a way to add the option of a real life-like, slowly adapting auto-exposure? Caves are too dark...

**Comment by istvanmate** [comment]
Can I adjust it directly? IRIS has no in game options implemented yet...

**Comment by Sildurs-shaders** [comment]
Most of the things that can be tweaked can be found inside the shaderpack in shaders.settings

**Comment by Sildurs-shaders** [comment]
Can be tweaked in the upcoming update.
