### ISSUE TITLE
Bug! Glowing Effect doesn't work.

### ISSUE THREAD

**Issue by P0PG03S** [Sildurs-shaders/sildurs-shaders.github.io#176]
Hi! First of all, I want to say these are the best shaders I have ever used.
Second of all, they have an excruciating bug: **"Glowing" effect doesn't work on any entities, players, and anything at all.**

I use it for my map, which heavily relies on Glow, I really hope this gets fixed.
_(Yes, I tried applying Glow with arrows and commands, neither of them work!)_

**Comment by P0PG03S** [comment]
**_(I use 1.29 version of Sildur's Vibrant Extreme on Minecraft 1.17.1...)_**

**Comment by Sildurs-shaders** [comment]
Iris supports this by default. Use that instead of optifine. A work in progress version for optifine is in the upcoming update.
