### ISSUE TITLE
Bug - World Border lines are black.

### ISSUE THREAD

**Issue by NoboKik** [Sildurs-shaders/sildurs-shaders.github.io#177]
Version: v1.29 Lite

Screenshot:
![image](https://user-images.githubusercontent.com/74139933/140171717-a2891ffb-a04b-4ad5-a3e2-58ca13cc9ae4.png)

**Comment by Sildurs-shaders** [comment]
Didn't make it into v1.30 but will be fixed with a hotfix soon.

**Comment by Sildurs-shaders** [comment]
fixed in hotfix coming out tomorrow
