### ISSUE TITLE
Weather [Rain, Snow] is broken with Iris in 1.18

### ISSUE THREAD

**Issue by NaiNonTH** [Sildurs-shaders/sildurs-shaders.github.io#179]
Specification:
OS: Windows 10
Minecraft Version: 1.18 Pre-release 1
Iris Version: 1.1.3-pre+rev.dc7aaef-dirty
Shader Version: 1.2.30 and older

I'll let screenshots explain you

![2021-11-16_22 51 10](https://user-images.githubusercontent.com/61338902/142019696-35af45d3-4e8b-492f-b72e-479bb922027d.png)
![2021-11-16_22 51 17](https://user-images.githubusercontent.com/61338902/142019789-87e2ca38-346d-484c-a85c-bd1396a8fc4f.png)
![2021-11-16_22 51 54](https://user-images.githubusercontent.com/61338902/142019806-b2c77375-8faf-4b64-bf69-905af146c7b2.png)

**Comment by NaiNonTH** [comment]
It was back to normal after I posted this. Not sure what fixes this.

**Comment by rshanule** [comment]
This bug is back
