### ISSUE TITLE
The mirror links on the website are still `adfoc.us`, you do realize some people have routers that block `adf.ly` links, right?

### ISSUE THREAD

**Issue by pjalsGit** [Sildurs-shaders/sildurs-shaders.github.io#180]

**Comment by Sildurs-shaders** [comment]
Adfly and adfocus are two different things, adfocus is harmless and most of the time just shows minecraft ads.

**Comment by pjalsGit** [comment]
Yes, but my router still blocks `adfoc.us`, and the point of mirrors is for it to be direct.
