### ISSUE TITLE
Grainy Shadows Bug

### ISSUE THREAD

**Issue by Comitant** [Sildurs-shaders/sildurs-shaders.github.io#181]
Ever since 1.28 there have been grainy shadows which gets more noticeable the further away you get, this remains the case even in 1.30. Also this gets even more noticeable after turning off TAA.

Here's an example of what I mean: https://imgur.com/a/ndr4us0 top image is 1.30 and bottom is 1.27. On the sand in the distance in the picture is where this can be seen best.

**Comment by Sildurs-shaders** [comment]
Fixed in upcoming version.
