### ISSUE TITLE
No Block Outline with Iris 1.18 on Enhanced Shaders

### ISSUE THREAD

**Issue by Anarchips83** [Sildurs-shaders/sildurs-shaders.github.io#182]
There is no block outline/border when you look at a block when using the Enhanced Shaders with Iris in 1.18.

**Comment by krystlerc** [comment]
Same, its hard to count the blocks because of this. lol

**Comment by ChloeDawn** [comment]
Further information from the Isis developer: https://github.com/IrisShaders/Iris/issues/929#issuecomment-982875981
