### ISSUE TITLE
Enchanted Tools and Weapons Turning White in Sildurs Enhanced Default V1.13

### ISSUE THREAD

**Issue by shark-yeen** [Sildurs-shaders/sildurs-shaders.github.io#183]
After downloading the new version and playing Minecraft 1.18 awhile with Optifine, I noticed that my enchanted sword and pickaxe would begin turning white around torches, and eventually would stay that way unless I turned off the shaders and turned them back on. My un-enchanted axe was fine, it was the same result for the Fast and Fancy versions regardless of whether I had the experimental ambient occlusion on or not.

https://user-images.githubusercontent.com/95666496/144957326-58e1c9a0-7eab-475f-8851-bf52dcdbe95e.mp4

.

**Comment by CasaBLAHca** [comment]
I have the same issue but I've narrowed down the issue its a problem with the custom light map idk how to fix it tho

**Comment by Sildurs-shaders** [comment]
Fixed in upcoming version, although enchanted items will be affected by custom colors, at least for right now.
