### ISSUE TITLE
Shader sun, moon on water and clouds & maybe water option 

### ISSUE THREAD

**Issue by Visitor2579** [Sildurs-shaders/sildurs-shaders.github.io#187]
When turned vanilla sun and moon water still uses round shader sun and moon, its buggy too + clouds are acting weird as well. 
Would you add option for vanilla water texture? Like FULLY no waves and stuff..? It's great shader which runs great but the water.

**Comment by Sildurs-shaders** [comment]
Default Sun, moon and clouds are working already, not sure about adding water support.
