### ISSUE TITLE
Malicious Download detected via monetized link

### ISSUE THREAD

**Issue by Bear-TheWolf312** [Sildurs-shaders/sildurs-shaders.github.io#19]
The ad fly link provided commits a drive-by download with a known MacOS trojan.

**Comment by Sildurs-shaders** [comment]
You should be fine by just pressing the skip ad button after 5 seconds, I have no control over which ads get displayed.

**Comment by Bear-TheWolf312** [comment]
It started the download immediately after clicking the adfly link.
