### ISSUE TITLE
Enchanted Item Lighting Bug

### ISSUE THREAD

**Issue by Discount5O** [Sildurs-shaders/sildurs-shaders.github.io#190]
All Enchanted items become blank/white when worn or held. I tested this with and without various resource packs and the bug is present regardless (image of the bug below).  Aside from that issue I have zero complaints, it's truly a beautiful and well-built shader pack. Well done!

![2021-12-12_23 58 12](https://user-images.githubusercontent.com/96036467/145755267-1266d1ce-3a94-40f7-95b3-f805ffbdd0d0.png)

**Comment by BorysSerbyn** [comment]
enhanced default fancy v1.13 on optifine 1.18.1. (tested on windows and popos)
I also encountered something similar (but not exactly). In my case, part or all of my enchanted item becomes white when exposed to certain light conditions [(see youtube video).](https://youtu.be/YlLhPC4fJxM) I'll let you draw your own conclusions from whats in the video, but I think the light level reflected by the enchanted armour is much brighter than the relatively dark cave i'm in.

**Comment by Sildurs-shaders** [comment]
This didn't happen in earlier optifine versions for older minecraft clients so this is currently marked as an optifine bug.
