### ISSUE TITLE
Disabling shadows also override vanilla shadows and lighting

### ISSUE THREAD

**Issue by REALMWTH** [Sildurs-shaders/sildurs-shaders.github.io#191]
Using Sildur's Enhanced Default, there are several issues when you disable shadows in shader's settings as seen at screenshots
Shaders disabled: 
![2021-12-13_07 00 42](https://user-images.githubusercontent.com/1342847/145755374-32cc939c-72d0-4f81-8a17-f3e1ee6988c0.png)
Shaders enabled:
![2021-12-13_07 00 37](https://user-images.githubusercontent.com/1342847/145755384-80ba9921-ba86-4d2c-8acd-9b4e091fedcf.png)

Also disabling shadows disables vanilla entity shadow (if it was enabled in settings)
![2021-12-13_07 04 45](https://user-images.githubusercontent.com/1342847/145755463-614a8609-2642-4e5d-b4d4-224805adfd0e.png)
I am using:
iris-mc1.18.1-1.1.3.jar
sodium-fabric-mc1.18.1-rc1-0.4.0-alpha5+build.813.jar

P.S. I am using shaderpack only to get TAA anti-aliasing, so I've disabled everything else :)

**Comment by Sildurs-shaders** [comment]
Fixed in upcoming version.
