### ISSUE TITLE
Issue with block breaking texture

### ISSUE THREAD

**Issue by REALMWTH** [Sildurs-shaders/sildurs-shaders.github.io#192]
Running any of your shader packs I have the block breaking texture bug
Shaders disabled:
![2021-12-13_07 08 57](https://user-images.githubusercontent.com/1342847/145755822-fc238978-3439-41f7-ba14-f8ece1bda90f.png)
Shaders Enabled:
![2021-12-13_07 08 50](https://user-images.githubusercontent.com/1342847/145755835-918671b1-2319-4149-adac-9cace3e3b0a5.png)
I am using:
iris-mc1.18.1-1.1.3.jar
sodium-fabric-mc1.18.1-rc1-0.4.0-alpha5+build.813.jar

**Comment by Sildurs-shaders** [comment]
Iris is still work in progress and has a bunch of bugs on their end, if it works with optifine it's working as intended and iris needs to be fixed.

**Comment by REALMWTH** [comment]
I am not sure if it's but of Iris because other shaders (such as Complementary) doesn't cause issues like this one.
