### ISSUE TITLE
[Suggestion] Saturation/Vibrance sliders?

### ISSUE THREAD

**Issue by Arrowpuppet** [Sildurs-shaders/sildurs-shaders.github.io#194]
I haven't seen this suggested much if at all for this shaderpack, so I may be in the minority for wanting this feature, but I just can't get over how lovely this pack is otherwise. I get that the whole point of "sildurs _vibrant_ shaders" is that it is, well, _vibrant,_ but I don't see how a little more customizability could hurt. I've looked at other packs that actually do have adjustable saturation, but they don't seem to come close to the quality of waves and caustics that this pack has, so this feature would just be a cherry of perfection on top of an already delicious cake. I'm open to hear y'alls thoughts on this as well!

**Comment by Sildurs-shaders** [comment]
Check the ingame options again, vibrant shaders has a bunch of color options to make it less vibrant.

**Comment by Arrowpuppet** [comment]
I've looked through the settings and I'm not sure what you're referring to. Under the "lighting colors" option, changing the options just changes the color balance, and lower settings just means its less bright, not less saturated. Am I missing something?

**Comment by Sildurs-shaders** [comment]
Simply adjust the contrast and brightness options in the color section. Increasing contrast actually reduces it. For example try something like, brightness 0.5 contrast 3.5.
