### ISSUE TITLE
Enchanted items are completely white (Enchanced Default Version 1.13 Fancy)

### ISSUE THREAD

**Issue by ArenPlaysGames** [Sildurs-shaders/sildurs-shaders.github.io#195]
Any enchanted items are completely whited out in Sildur's Enhanced v1.13 Fancy when you have the Custom Lightmap on.
![2021-12-20_02 10 36](https://user-images.githubusercontent.com/33564022/146733979-27fd4b59-5a31-42ec-81a2-ed8c77956ee8.png)

**Comment by Sildurs-shaders** [comment]
fixed in upcoming update.
