### ISSUE TITLE
v1.32 cannot be downloaded

### ISSUE THREAD

**Issue by Heath123** [Sildurs-shaders/sildurs-shaders.github.io#196]
As you can see here:
https://github.com/Sildurs-shaders/sildurs-shaders.github.io/blob/a3e474acfb199dfe7a7b03a70c24bab5537bcd81/downloads/index.html#L255
the href is blank, so the shader cannot be downloaded.

**Comment by Sildurs-shaders** [comment]
It's in Patreon early access.

**Comment by Heath123** [comment]
> It's in Patreon early access.
@Sildurs-shaders Please can you make the site mention this, rather than just leaving a broken link?

**Comment by Sildurs-shaders** [comment]
It literally has the date in it and Patreon early access next to it. And above the downloads it says: "Like my work? Consider supporting me on Patreon to keep it going and get early access!"

**Comment by Heath123** [comment]
> It literally has the date in it and Patreon early access next to it. And above the downloads it says: "Like my work? Consider supporting me on Patreon to keep it going and get early access!"

I don't see how I was supposed to supposed to know from the date that it wasn't available to download, and I would assume that anything available on the download page with a link is available for download. Anyway, I'll make a PR with something that would be clearer to me
