### ISSUE TITLE
Beacon beam is always black

### ISSUE THREAD

**Issue by MrLuxALot** [Sildurs-shaders/sildurs-shaders.github.io#198]
The beacon beam is always black with the Enhanced Default shader. It works fine with the Vibrant ones but i dont want to use them
![2022-01-01_22 48 09](https://user-images.githubusercontent.com/52431814/147860858-fcef702e-0e21-49e7-9233-cb640b141042.png)
.

**Comment by xanthian** [comment]
Same on my world also.

Fabric 1.18.
Iris, Sodium, Indium

**Comment by Sildurs-shaders** [comment]
Should work fine on optifine, so mod issue.
