### ISSUE TITLE
Flickering bug in translucent materials?

### ISSUE THREAD

**Issue by Nemeruis** [Sildurs-shaders/sildurs-shaders.github.io#2]
when I use this shader everything that is transparent is bugged(mostly mod stuff). I tried many options but couldnt fixed it. Can I fix this?
![2019-06-16_13 40 12](https://user-images.githubusercontent.com/51802500/59562956-54ffd280-903c-11e9-82a4-3cef5262ca62.png)
![2019-06-16_13 40 16](https://user-images.githubusercontent.com/51802500/59562957-57fac300-903c-11e9-946d-ac2508c1c6ad.png)

**Comment by Sildurs-shaders** [comment]
Shadersmod is having alot of issues with modded blocks, there's not much I can do about it. Enhanced default might work since it's rendering approach is more basic and closer to vanilla.
