### ISSUE TITLE
No weapon enchantment glow for Enhanced Default

### ISSUE THREAD

**Issue by hkight** [Sildurs-shaders/sildurs-shaders.github.io#201]
Whenever using the Enhanced Default shaders, the weapon and armor enchantments don't work. They just render as un-enchanted. Tested with both Iris and Optifine, on both 1.17 and 1.18.1 and neither works.

![2022-01-06_13 53 43](https://user-images.githubusercontent.com/18399988/148435835-1f1f014f-1928-484e-aa7a-34a053496c4b.png)
Enhanced Default 1.131

![2022-01-06_13 53 56](https://user-images.githubusercontent.com/18399988/148435839-5e4970d6-f7db-4162-9e06-b4a7039d7bfc.png)
Vibrant Shaders 1.32

Vibrant Shader enchantment glow works fine.

**Comment by Sildurs-shaders** [comment]
It works in both versions, tested on optifine 1.19. Enhanced default currently suffers from a white bug though.
