### ISSUE TITLE
Website flagged as phishing?

### ISSUE THREAD

**Issue by Zafpyr** [Sildurs-shaders/sildurs-shaders.github.io#203]
![image](https://user-images.githubusercontent.com/11844204/148672966-3abc8395-647b-4fb1-a909-4f95c70987cf.png)

Hi, the sildurs-shaders.github.io is being flagged as phishing by my antivirus, Avast. 
I know it's obviously not, but why is it being flagged as such and what can be done?

**Comment by Sildurs-shaders** [comment]
There was an issue with my previous ad partner and it flagged the site months ago. I went through the whole google verification process to unflag it. Unfortunately some antiviruses, browsers and such still have it falsely flagged.
