### ISSUE TITLE
[Sildur's Vibrant Shaders] Only blocks within the player's chunk are considered for shadow calculations

### ISSUE THREAD

**Issue by PencilVoid** [Sildurs-shaders/sildurs-shaders.github.io#204]
Refer to the attached screenshots. In the first screenshot only the wall behind me is casting a shadow, since the rest of the room is in a different chunk to me. As a result, the lighting in the room appears unnatural as light appears where it shouldn't. In the second screenshot I have moved forwards into a different chunk. As such, the other walls of the room now cast shadows but the wall behind me no longer does, and areas that were previously dark are now bright. This effect isn't very noticeable outdoors, but quickly becomes jarring indoors. This doesn't occur when using the Enhanced Default shaderpack. Turning on the raytraced shadows option has no effect, but it may be because my processor uses Intel HD Graphics which possibly doesn't support raytracing. Increasing the shadow distance slider also has no effect. Configured using Optifine, tested with Iris+Sodium+Indium and version 1.3.2 Lite of Sildur's Vibrant Shaders.

![2022-01-09_12 39 39](https://user-images.githubusercontent.com/83508866/148684584-72409697-9cd7-4bbb-9a7e-0068c77739c8.png)
![2022-01-09_12 39 41](https://user-images.githubusercontent.com/83508866/148684591-98450690-ef64-4799-a37d-41bd45dbc9a5.png)

**Comment by Sildurs-shaders** [comment]
Can't do anything to the way the shadersmod does things. In low light areas shadows are turned off to prevent light leaking.
