### ISSUE TITLE
A way to change lighting effected in compact machines?

### ISSUE THREAD

**Issue by Tasenova99** [Sildurs-shaders/sildurs-shaders.github.io#205]
[I](url) have concluded that inside of Compact machines 3 when using shaders it only works in the daytime, the right textures I mean, when the time changes outside in the world, it had a visual glitch like debugging mode. In this screenshots here, you can see the time of day in the top right corner and how it is effecting the visuals

https://imgur.com/a/muNuRc5

This, is an easy solution, switch game to lan and change set time to 0

However, I was wondering if its possible to take the lighting out of a certain block like the END, where there is no sky, so there is no glitch, is there a way to have the sky lighting turned off in the compact machine?
because then people who play this mod with shaders, doesn't have to set the time to 0 or worry about it, they just have to change a setting or two.

In something like astral sorcery, it is a visual sky box conflict, so you could turn off the custom sky in the astralsorcery.cfg 

but there is no custom sky in the compact machines, so the only way it could be fixed is if you could turn off the lighting in this area? in this compact machine?

very specific complex question, set it to low priority if you must

**Comment by Sildurs-shaders** [comment]
Enhanced Default should be used with mods instead since it's rendering approach is very close to vanilla minecraft, working way better with mods.
