### ISSUE TITLE
Sildurs Enhanced doesn't support custom lava colormap.

### ISSUE THREAD

**Issue by HaragOnMC** [Sildurs-shaders/sildurs-shaders.github.io#206]
In my resource pack, I turned my lava into a white texture to make the lava having a biome depend texture. The problem is the shader show the lava white texture instead of the custom colormap I made for lava.

**Comment by Sildurs-shaders** [comment]
Make sure you are using the latest version, custom lightmaps for lava were fixed in v1.30.
