### ISSUE TITLE
Entities become invisible when on other chunk then the player and weird shadows

### ISSUE THREAD

**Issue by zinixyt** [Sildurs-shaders/sildurs-shaders.github.io#207]
I'm playing a modpack called Another Quality Modpack 2 on 1.18 that uses sodium and iris, but i get some weird problems:

- Entities only render when on the same chunk as me
- Shadows change from one chunk to another
- Shadows mentioned above don't render properly inside buildings(ex. Sunlight inside a house)

I can't find the shaders custom options menu like on optifine if that's a thing.
All of my friends have this problem, so it's not system-specific.

**Comment by TheAnachronism** [comment]
I have the same problem…
Other shaders don't do this, but a friend of mine uses an older version of sildur, but he doesn't have it, even though on my machine with the same version, that problem is there.

**Comment by Sildurs-shaders** [comment]
Mod issues, everything is working fine on 1.19 with optifine.
