### ISSUE TITLE
tremble/flicker effect with TAA since v1.30 | completly broken with TAA since v1.50

### ISSUE THREAD

**Issue by Pilzinsel64** [Sildurs-shaders/sildurs-shaders.github.io#209]
Hello.

In version 1.30+ there is a weird flicker/tremble effect on the Laptop for me and my girl friend.
It goes away when disabling TAA, but that's not a good solution in my opinion.

See this video here:
~~https://cloud.pilzinsel64.de/s/7XXrzbYoBYNrFPH~~ (auto deleted, tell me if you need it again)
First I show you how it looks with v1.29, then I show it with v1.32 and then with v1.32 but without TAA.

My graphics card and driver:
NVIDIA GeForce GTX 980M
Driver version: 25.21.14.1935
Driver date: 01.03.2019 (yes, there aren't newer versions that are compatiblem, sadly)
Note: I don't remember exactly what it was for my girl friend, but a little bit better and newer and also NVIDIA GeForce GTX:

Some other infos:
![grafik](https://user-images.githubusercontent.com/23138465/152375040-2a8b50b9-1d21-44d4-8a41-da1ce9fe65fc.png)

Any ideas? 🤔
My personal thought is that it has something todo with Minecraft 1.7.10.

**Comment by Sildurs-shaders** [comment]
I think there were some other issues with TAA on 1.7.10, so either use an older version or keep it disabled.

**Comment by Pilzinsel64** [comment]
Alright, so for us, we keep the old version then.
Thank you very much for your answer! ^^

**Comment by Pilzinsel64** [comment]
@Sildurs-shaders Tested again with v1.50 as the changelog has improved TAA listed.
Now with v1.50 on Minecraft v1.7.10 it's even more crisly, sadly, take a look: https://cloud.pilzinsel64.de/s/AmQyPq7HYWBRxxm
So I guess the time of the Shader is over now and can't continue to support v1.7.10 with newer versions, at least with TAA enabled by default. At least I didn't find any option to fix this, except disabling TAA and use FXAA from OptiFine (not the best solution, but better then nothing). Anyways, even v1.50 works nicely on v1.7.10.

**Comment by Pilzinsel64** [comment]
Alright, confirmed that TAA is working fine on Minecraft 1.20.6 with Fabric+Iris and Forge+OptiFine and Sildur's Vibrant Shaders v1.5.1 Extreme on the same machine where it won't work on 1.7.10 Forge.

**Comment by Sildurs-shaders** [comment]
Due to a lot of changes to the rendering pipeline I don't think I can continue to support TAA in vibrant shaders for MC 1.7.10. It will be auto disabled in the next update.

**Comment by Pilzinsel64** [comment]
@Sildurs-shaders Can you please enable it back on? The new Iris backport might support it again. I'm consolidating the last few issues using Angelica + Sildurs. However, I just can't test the antialias thing as I toggling it on/off doesn't has any affect.
