### ISSUE TITLE
Rain reflections appearing even when inside

### ISSUE THREAD

**Issue by victorvansande** [Sildurs-shaders/sildurs-shaders.github.io#21]
I love the wet reflections on the ground when it's raining, but i don't like that the effect also shows when inside. It would look better if the floor would be 'dry' whenever you enter a building.

It might be tricky to fix, but love to see it change.

[Picture](https://imgur.com/a/Imzuk8q) for reference

**Comment by Sildurs-shaders** [comment]
Yeah it's on the todo list, but very tricky to pull of.

**Comment by Sildurs-shaders** [comment]
Will be fixed / improved the upcoming update.
