### ISSUE TITLE
Wrong irradiance map rendering 

### ISSUE THREAD

**Issue by CongYuSanXun** [Sildurs-shaders/sildurs-shaders.github.io#211]
mod is betterend（ https://github.com/paulevsGitch/BetterEnd  ）
![huge_2022-02-18_14 11 05](https://user-images.githubusercontent.com/68322529/154679338-91016bb1-f16f-4303-86e2-9ace7591916b.jpg)
![huge_2022-02-18_14 14 45](https://user-images.githubusercontent.com/68322529/154679344-26be2ff1-d953-4cba-9241-115b2f1881c3.jpg)

 irradiance map file
![image](https://user-images.githubusercontent.com/68322529/154679402-792c4cbc-e37a-4ba1-9e60-93c7be47228a.png)
end_slime_lake_glow.png

**Comment by Sildurs-shaders** [comment]
You might have to adjust the texture properties to fix this.
