### ISSUE TITLE
weird water bug

### ISSUE THREAD

**Issue by Icyy1** [Sildurs-shaders/sildurs-shaders.github.io#212]
I get this weird water bug that happens with glass and portal blocks. Sometimes it works as normal but most of the time its like this (also happens with other shader packs such as wisdom and oceano) it also works perfectly when zoomed in on optifine.
![image](https://user-images.githubusercontent.com/98864252/155061765-4655a94e-3d1e-4acb-aa2e-1ecbfe5c6294.png)

**Comment by Sildurs-shaders** [comment]
Sounds like a mod issue, closed for now.
