### ISSUE TITLE
Wet Caves and puddles

### ISSUE THREAD

**Issue by Jotaseca** [Sildurs-shaders/sildurs-shaders.github.io#213]
I've been mining a lot using this shader, and I never really enjoyed using it in caves. There isn't really any difference between the ambience in the outside and the caves, besides the brightness (also there is a bug where the god rays enter the caves when looking in long distances). 
I suggest adding a feature, where the textures get wet the deeper you go, because of the temperature. This shouldn't be hard to code, you can just set it to the deeper you go, the more reflections a texture gets. 
Also, in the surface, if you want to go further you could code like some patches in the ground where the textures are a lot more reflective, so it looks like puddles, and give it some rain falling on them effect when it rains.
Thank you for reading this.

**Comment by Sildurs-shaders** [comment]
Maybe for the vibrant shaders rework, but closed for now.
