### ISSUE TITLE
Rapidly flickering white dots along chunk borders

### ISSUE THREAD

**Issue by locque** [Sildurs-shaders/sildurs-shaders.github.io#215]
![2022-03-15_11 15 26](https://user-images.githubusercontent.com/29549891/158356518-6232f175-0930-4bf5-a99a-e01945ef4b34.png)

These artifacts appear at every chunk border in dark areas.

Tested with most quality levels of the 1.32 vibrant shaders on a GTX 970, drivers are up to date. I also did a reset of all the nvidia control panel settings, some people mentioned antialiasing and anisotropic filtering settings not being set to appliction controlled interfering and causing this issue.

**Comment by Sildurs-shaders** [comment]
Shadersmod issue I think, closed for now.
