### ISSUE TITLE
Suggestions to Vanilla Enhanced Default

### ISSUE THREAD

**Issue by ENTPRESTIGIOUS** [Sildurs-shaders/sildurs-shaders.github.io#217]
Is it possible to implement pbr, normal mapping and that stuff into the vanilla enhanced default? The reason being is that I want emissive ores and the only way to get that is through those settings.

**Comment by Sildurs-shaders** [comment]
Enhanced default supports bump and parallax mapping in the ingame settings.  Full PBR might be added in the future.
