### ISSUE TITLE
(Sildur's Vibrant Shaders) No border fog

### ISSUE THREAD

**Issue by Pectacular** [Sildurs-shaders/sildurs-shaders.github.io#218]
There is no border fog in the Sildur's Vibrant Shaders as shown in the below screenshots:
![2022-04-14_17 56 26](https://user-images.githubusercontent.com/54170867/163390419-0cd6f52c-6a99-4c5e-90d0-5d6564893955.png)
![2022-04-14_17 56 29](https://user-images.githubusercontent.com/54170867/163390426-b9a229bc-f06c-4c7d-8649-a89248d4a7aa.png)

**Comment by Sildurs-shaders** [comment]
Fixed in upcoming version.
