### ISSUE TITLE
Textures break when joining worlds

### ISSUE THREAD

**Issue by SeanIsDumb** [Sildurs-shaders/sildurs-shaders.github.io#220]
Whenever I play a server and transfer to another world, the textures all condense and glitch out. This can be stopped by reapplying the shader but it gets annoying after the 5th time. This happens with **Sildur's Vibrant Shaders Lite, Medium, and Sildur's Enchanted Default Fancy, and Fast**

Visual Evidence w/ Sildur's Vibrant Shaders Medium in Origin Realm:
![2022-04-23_15 09 49](https://user-images.githubusercontent.com/104280389/164947642-e5078ff5-b725-40b8-8ea0-202b6d157f12.png)
![2022-04-23_15 09 57](https://user-images.githubusercontent.com/104280389/164947644-0146e0ae-900e-41be-8ad2-ebb7d0852039.png)
![2022-04-23_15 10 20](https://user-images.githubusercontent.com/104280389/164947645-7ab375d8-4968-4a74-a505-62accbe0b214.png)
![2022-04-23_15 10 52](https://user-images.githubusercontent.com/104280389/164947646-be83bbce-8271-46bb-8959-c5e3d055b68f.png)

**Comment by Pectacular** [comment]
I'm pretty sure this is an Iris-only issue

**Comment by Pectacular** [comment]
Also instead of toggling shaders off and then on, just reload all the chunks

**Comment by Sildurs-shaders** [comment]
F3+R will reload the shaders, at least in optifine.
