### ISSUE TITLE
Glow item frame content.

### ISSUE THREAD

**Issue by Psychodeus** [Sildurs-shaders/sildurs-shaders.github.io#222]
I'm using Fabric 1.18.1 & LambDynamicLights mod

When I turn off the shaders the item attached on glow item frame is distinguishable.
![image](https://user-images.githubusercontent.com/93028949/165449735-e85c1c19-d42c-4cc3-88fd-42843fe62b6a.png)

But, if I turn on the shaders the item attached is so bright, it becomes indistinguishable.
![image](https://user-images.githubusercontent.com/93028949/165449752-3af24136-72d5-4151-9f26-218f95ed4d5a.png)

Then if I turn off the **Glow item frame** from **Dynamic Light Sources: Entities**, it still indistinguishable.
![image](https://user-images.githubusercontent.com/93028949/165449766-97258fbe-34e1-4667-ad36-9c7faf889a6f.png)

And I've open an Issue to the owner's GitHub page and this is the response
![image](https://user-images.githubusercontent.com/93028949/165450164-ddbba631-0950-43e7-ab9a-cba348060f13.png)

Could you make it distinguishable when I turn the shaders on? Without making the item attached as light source or something.

**Comment by Sildurs-shaders** [comment]
They are marked as glowing entities in the shadersmod and so bloom is applied to them. You could turn off bloom in the ingame options to reduce the overall brightness.
