### ISSUE TITLE
Random items make screen bright 

### ISSUE THREAD

**Issue by Vwhbj2003** [Sildurs-shaders/sildurs-shaders.github.io#223]
When using sildurs, an apple or iron axe will make everything on screen very bright. Brighter than daylight. So far it's only with those two items. If I switch to seus they only get as bright as a normal torch. Turning shaders off gets rid of the effect. I've seen people post similar problems on reddit for optifine with no help. I'm not sure if this is a optifine problem or shaders. I'm just trying every place I can to get some help. This is my first time posting so let me know if I'm going about this wrong.

**Comment by Sildurs-shaders** [comment]
Sounds like a shadersmod issue. So optifine and iris related.
