### ISSUE TITLE
Weird visual glitch

### ISSUE THREAD

**Issue by Romanlab1** [Sildurs-shaders/sildurs-shaders.github.io#225]
[](url
![2022-06-22_20 14 54](https://user-images.githubusercontent.com/108023404/175108022-648fc0ad-edc7-4ba0-9e5c-467bbbd8b39b.png)
![2022-06-22_19 07 15](https://user-images.githubusercontent.com/108023404/175108031-08f5e60c-a399-428b-a477-ef672c2067e1.png)
)

**Comment by afonso325** [comment]
its the same thing for me, already reinstalleded everything and didnt work

**Comment by Sildurs-shaders** [comment]
Update your gpu drivers, for nvidia latest version can be found here, v516.79:
https://www.guru3d.com/files-details/geforce-516-79-hotfix-driver-download.html
