### ISSUE TITLE
Light through blocks

### ISSUE THREAD

**Issue by krazeral** [Sildurs-shaders/sildurs-shaders.github.io#226]
I've been using these shaders for a long time and this bug was always there, but now it started to bother me more, because it breaks the atmosphere of the game. 

![image](https://user-images.githubusercontent.com/76794093/175772999-0ff5a17c-d2b9-4d14-aede-877ea4c614e1.png)

**Comment by Sildurs-shaders** [comment]
That's an issue with minecraft rendering and shadersmod, dealing with chunks. In my shaders shadows will be turned off at low light areas, preventing this. Might be improved in future versions but there's only so much shaders can do about this.
