### ISSUE TITLE
Strange bug that effects chests creepers and more.

### ISSUE THREAD

**Issue by Jesras** [Sildurs-shaders/sildurs-shaders.github.io#227]
So as far as I noticed I'm having problem with wooden chest; creepers, skeleton bones, bows.
![2022-07-05_07 05 19](https://user-images.githubusercontent.com/69968114/177250108-73748920-259c-44c6-943e-73df5534e61b.png)
 
![2022-07-05_07 05 30](https://user-images.githubusercontent.com/69968114/177250183-187cbb9f-9949-494f-ba90-d6d696177640.png)
![2022-07-05_07 05 32](https://user-images.githubusercontent.com/69968114/177250238-ab0b5ba4-78bc-4714-9d01-cca8b4630520.png)
![2022-07-05_07 19 45](https://user-images.githubusercontent.com/69968114/177250306-e39674f0-8bf5-46f3-b488-f76323969d0d.png)
![2022-07-05_07 29 13](https://user-images.githubusercontent.com/69968114/177250360-78e54bb7-302b-4371-8655-6b4398207380.png)
![2022-07-05_07 29 17](https://user-images.githubusercontent.com/69968114/177250407-3b6d435f-64fc-427f-a3dc-3172174871ee.png)
![2022-07-05_07 29 21](https://user-images.githubusercontent.com/69968114/177250450-f6e316da-3ff8-440f-a2fd-f0519762beca.png)

I'm using oculus 1.2.5 with rubidium 0.2.6 
Also using Unity resource pack with dark edition + modded edition (problem still occurs even resource pack is deactivated.) 
Note: The creepers and skeleton bows are sometimes work appropriate, generally brokes when they start to get out of the frame. 
wooden chest on the other hand, never looks as intended. I haven't played my newly created mod list yet so, IDK if there are more things as such, but these are the ones I found out while messing around. 
Thank you for the shader pack looks quite nice!!

**Comment by Sildurs-shaders** [comment]
Maybe shadersmod issue in optifine and iris. But in general enhanced default should be used with mods as it supports them way better due to the way I wrote it, being close to vanilla mc rendering.
