### ISSUE TITLE
Silders Enchanced Default does not like GoG SkyBox

### ISSUE THREAD

**Issue by VanillaChan6571** [Sildurs-shaders/sildurs-shaders.github.io#23]
![2019-10-03_09 42 24](https://user-images.githubusercontent.com/39040261/66142223-47a62e00-e5c2-11e9-9f25-994b3062654c.png)
![2019-10-03_09 42 47](https://user-images.githubusercontent.com/39040261/66142224-47a62e00-e5c2-11e9-86ff-2d7e7ce9abb5.png)

**Comment by Sildurs-shaders** [comment]
Enhanced default rendering is based on vanilla MC, if it still breaks a mod there's not much that can be done about it.
