### ISSUE TITLE
weird bars on the ground and all the blocks near you

### ISSUE THREAD

**Issue by kendii830** [Sildurs-shaders/sildurs-shaders.github.io#230]
Bars appear on every block near me, not sure if that's a bug or not. But need help with tha
![2022-07-28_06 39 52](https://user-images.githubusercontent.com/54154953/181384906-c3a04be0-3029-4d51-a86d-db1484d96b47.png)
![2022-07-28_06 37 44](https://user-images.githubusercontent.com/54154953/181384920-c81781fd-9ebf-43a4-946d-c930541d176b.png)
t

**Comment by Sildurs-shaders** [comment]
Update your nvidia drivers, latest version: https://www.guru3d.com/files-details/geforce-516-79-hotfix-driver-download.html
