### ISSUE TITLE
Basic Shaders v2.0 download link is broken

### ISSUE THREAD

**Issue by 0x000006** [Sildurs-shaders/sildurs-shaders.github.io#231]
Expected behavior:
I click a download link, go through adfoc.us and it redirects me to Curseforge

What actually happens:
I click a download link, go through adfoc.us and it redirects me to the Curseforge 404 Not Found page

**Comment by Sildurs-shaders** [comment]
You should have read the tweet or facebook message again, I said it is under review, it's live now.
