### ISSUE TITLE
[Enhancement] Add an option in shaders.settings to allow users to disable the newly-implemented chunk border fog as of 1.40.

### ISSUE THREAD

**Issue by akemin-dayo** [Sildurs-shaders/sildurs-shaders.github.io#232]
It would be nice if an option could be added to `shaders.settings` to allow users to disable the newly-implemented chunk border fog as of 1.40.

The current behaviour causes the chunk border fog to always be present, even if fog is disabled by the end user.

**Comment by Sildurs-shaders** [comment]
Fixed in upcoming version.
