### ISSUE TITLE
Basic Shaders shadows seem to be inverted

### ISSUE THREAD

**Issue by NaiNonTH** [Sildurs-shaders/sildurs-shaders.github.io#234]
## Description
I'll let the screenshot describe the issue itself.

![2022-08-12_15 38 13](https://user-images.githubusercontent.com/61338902/184317703-41ed52c5-23a2-4bf6-85bf-60609623eef0.png)

## Additional Info
**Minecraft Version:** _1.19.2_
**Iris Mod Version:** _1.2.7-pbr-beta.10 (Download is available via Iris Official Discord Server)_

**Comment by NaiNonTH** [comment]
Iris was used in the screenshot.

**Comment by Sildurs-shaders** [comment]
As far as I know this is caused by the pbr beta. Use the standard version of iris instead.

**Comment by NaiNonTH** [comment]
Seems to be like what you'd said. I'll report this issue to Iris Discord Server and hope this issue will eventually be fixed.

## Feature Request
But hey, it would be ideal to add basic shadows—something like this issue but reverted—into your basic shaders as an optional feature.

**Comment by NaiNonTH** [comment]
It seems to be already fixed recently, but not in the version I used.

**Comment by NaiNonTH** [comment]
Will reopen this if the issue still occurs in the next version of Iris.
