### ISSUE TITLE
Banner Flickering Still a Major Problem

### ISSUE THREAD

**Issue by Morabert** [Sildurs-shaders/sildurs-shaders.github.io#235]
Banner Flickering is Intense. Turning off Antialiasing causes banner flicker to stop but still loads banner textures improperly.
MC: 1.16.5
Forge 36.2.25
Sildur's Vibrant Extreme 1.40 (Issue also occurs with "Basic 2.0 & "Enhanced Default 1.14, both "Fancy")
First Image; With Antialiasing ON:
![Screenshot_209](https://user-images.githubusercontent.com/36409264/184742281-990ae438-0e95-4767-8b12-b511b8dd5b52.png)

Sceond Image; With Antialiasing OFF:
![Screenshot_208](https://user-images.githubusercontent.com/36409264/184741306-31d5dcc4-472f-4dcb-b859-a45d719ad4e0.png)

Third Image; With Shaders OFF (AKA functioning Banner Render):
![Screenshot_210](https://user-images.githubusercontent.com/36409264/184742042-c3addcd4-684a-422f-990f-c9b07e89de94.png)

**Comment by Sildurs-shaders** [comment]
Can't reproduce on 1.19.2 with Iris, this might be an optifine bug.
