### ISSUE TITLE
macOS // Apple Silicon // significantly huge performance drop with specific shaders and orange glow around shapes

### ISSUE THREAD

**Issue by pummeluff365** [Sildurs-shaders/sildurs-shaders.github.io#236]
It´s my first time reporting an issue on github. Fingers crossed I will do it correctly.

**used hard- and software**
- MacBook Pro 14' // M1 Pro // 10-core GPU // 16GB RAM // macOS 12.5
- official Minecraft // 1.19.2 (M1 compatible) // [zulu JDK with M1 compatibility](https://www.azul.com/downloads/?version=java-18-sts&os=macos&architecture=arm-64-bit&package=jdk)
- Fabric install // Sodium, Lithium, Phosphor (last 2 should have no impact; I installed them after in the hopes to solve the issue)

**Problem(s)**
When choosing the Vibrant Shaders _Medium_ everything works and performs just fine.
But with _High & Basic Fancy_ performance is just terrific. It just doesn´t seem to be linear performance requirements.

Additionally as long as I have played on macOS there is some kind of orange glow around almost every shape edge.
I hope the pictures are included in this post.

If you need more details or specific things I should try, let me know.

![Basic Shaders :: poor performance](https://user-images.githubusercontent.com/111358821/184876831-e9d344b2-ec55-45ca-b897-5c9c4600551e.png)
![Vibrant Shaders High :: poor performance](https://user-images.githubusercontent.com/111358821/184876878-1d71589b-d1a0-4451-a5c6-f11d0f72d4dc.png)
![Vibrant Shaders Medium :: solid performance](https://user-images.githubusercontent.com/111358821/184876913-98fe0fb4-679f-4015-9420-0d8498f3e8c1.png)

**Comment by akemin-dayo** [comment]
The severe performance drop is caused by SSDO, and the "glow" artifacting around objects is caused by bloom.

As long as you disable SSDO, even Sildur's Vibrant Extreme will run well on Apple Silicon.

**Comment by pummeluff365** [comment]
Thank you very much 🙏

I just tried turning SSDO off and everything works just fine. I didn't know that this is an issue.
And I will take a look into the bloom situation.
