### ISSUE TITLE
Extreme overload in 3rd person mode (caused by block outline & hitboxes)

### ISSUE THREAD

**Issue by Felix14-v2** [Sildurs-shaders/sildurs-shaders.github.io#237]
When you switch your view to 3rd person mode and look into blocks, FPS drops incredibly: https://youtu.be/xEVZnr73eUQ (Sorry for low fps, OBS cuts it in half)
This also happens when hitboxes are enabled.

Shader used: Sildur's Vibrant Shaders v1.40 Lite
IrisShaders: 1.3.0 rc.4
Minecraft: 1.19.2
GPU: GeForce 9600M GT

**Comment by Sildurs-shaders** [comment]
Might be a driver bug, I think your gpu is just overloaded in general. You should try out enhanced default instead of vibrant shaders with a system like yours. https://www.curseforge.com/minecraft/customization/sildurs-enhanced-default
