### ISSUE TITLE
"Ghosting" with water reflections

### ISSUE THREAD

**Issue by Sobga** [Sildurs-shaders/sildurs-shaders.github.io#239]
A weird "reflection" appears when the bottom of the blocks  are exposed near water (see images). The expected reflection is also present (see image 2).

Using: 
 - Iris v1.3.1
 - Sildur's Enhanced Default v.1.14
 
Image 1 - The "ghosting" close-up)
![2022-09-19_11 35 26](https://user-images.githubusercontent.com/43469344/190989986-e48b41ac-695d-4332-8178-2860f713e5c6.png)

Image 2 - Both "ghosting" and proper reflection shown)
![2022-09-19_11 48 23](https://user-images.githubusercontent.com/43469344/190991954-c391ae1f-4601-4c15-9005-8f09adc7a8f4.png)

**Comment by Sildurs-shaders** [comment]
That is a limitation of screen spaced reflections, there are some workarounds but the more you add to it the slower it becomes. If you feel like reading in on it just search for screen spaced reflections.
