### ISSUE TITLE
Shaders Are Glitched?

### ISSUE THREAD

**Issue by crapedee3** [Sildurs-shaders/sildurs-shaders.github.io#241]
So I cant really explain it here is an image tho
<img width="1440" alt="Screen Shot 2022-09-20 at 12 04 54 pm" src="https://user-images.githubusercontent.com/109503850/191151426-55b4afba-6c42-4ca6-915f-d551d4cbf4ee.png">

**Comment by Sildurs-shaders** [comment]
Make sure your gpu drivers are up to date, they sometimes cause glitches like that.
