### ISSUE TITLE
Black screen when world is loaded/loading screen wont come off

### ISSUE THREAD

**Issue by SamyStar** [Sildurs-shaders/sildurs-shaders.github.io#243]
i have tried opening again minecraft, but it just doesnt work! What do i do??
But it still makes noises like i am actually playing, for example: walking on grass noises, and breaking dirt blocks.

**Comment by Sildurs-shaders** [comment]
Sounds like an optifine issue / mod issue, try updating everything including your gpu drivers and try again, reopen if it still happens.
