### ISSUE TITLE
Transparent grass (non-block)

### ISSUE THREAD

**Issue by Milennin** [Sildurs-shaders/sildurs-shaders.github.io#246]
Grass (non-block) appears fully transparent when viewed in the light. GPU (RTX 2070 Super) drivers are up to date. Screenshots are of viewing the same grass tile from 2 different angles:
![2022-10-11 19_50_51-Greenshot](https://user-images.githubusercontent.com/68442839/195167718-eb53d694-8801-4c4f-97ee-e3b78ae0eaff.png)
![2022-10-11 19_50_47-Greenshot](https://user-images.githubusercontent.com/68442839/195167734-546e9e0a-7bcf-4655-a9a2-b69ce35f6def.png)
Can provide more info, if necessary.

**Comment by Sildurs-shaders** [comment]
Double check that everything on your end is up to date, if it still happens reopen this issue.
