### ISSUE TITLE
celshading doesnt work on water in vibrant shaders

### ISSUE THREAD

**Issue by retr0scape** [Sildurs-shaders/sildurs-shaders.github.io#247]
in the vibrant shaders the edges of water are not celshaded, they lack a black outline. however, the same issue is not present in the basic shaders or enhanced default shaders.

the first image is the vibrant shaders, the second is enhanced default.
![image](https://user-images.githubusercontent.com/53084723/195219696-7b219384-d2fd-4d72-a278-ed49b378395f.png)

![image](https://user-images.githubusercontent.com/53084723/195219885-8268db41-5ba2-416b-a2d7-3d3a853251ac.png)

i know its a bit hard to even notice but it bothers me, especially when i change the thickness of the outline.

**Comment by Sildurs-shaders** [comment]
The way of rendering transparency is completly different, so this probably won't be fixed in vibrant shaders. Maybe in the rework though.
