### ISSUE TITLE
Download links redirect to malware+marijuana sites instead of advert timer

### ISSUE THREAD

**Issue by NexusDarkshade** [Sildurs-shaders/sildurs-shaders.github.io#250]
Hello, I tried opening your download links (the ones that go through ad focus), but instead of going to the ad wait countdown, they instead redirect to malware downloads or (possibly illegal) marijuana sites. I had to open in a new private window to even get it to load the ad focus page.

**Comment by Sildurs-shaders** [comment]
I forwared this and other issues to the advertising company and they are working on filtering out any weird ads like that.
