### ISSUE TITLE
Enhanced Default Shader not working properly (Both Fast and Fancy version)

### ISSUE THREAD

**Issue by tangymc** [Sildurs-shaders/sildurs-shaders.github.io#252]
![image](https://user-images.githubusercontent.com/74885686/200775394-41a7d5b0-52e2-4619-a508-865af343e47b.png)

**Comment by Sildurs-shaders** [comment]
Are you using forge? That's a forge bug, restart your game.

**Comment by Pinecone6442** [comment]
works for me on forge lol
