### ISSUE TITLE
Shader causing the End to appear pitch black

### ISSUE THREAD

**Issue by Cryptillian** [Sildurs-shaders/sildurs-shaders.github.io#253]
Hi I have been running these shaders for 1.16.5 with no issue until I go to the End and noticed everything is pitch black. I tried resetting all settings, reinstalling/donwloading shaders, downloading older versions, nothing seems to work. If I turn off the shaders everything will appear normal so I've concluded it must be an issue on the shader's side.

![image](https://user-images.githubusercontent.com/52714644/201539644-d7f31ed7-7498-4088-a6d5-4051c162c927.png)

I am using Forge 36.2.39 and OptiFine HD U G8
I am using the BetterEnd mod in case that is relevant as well.

**Comment by Cryptillian** [comment]
Ah so I found the reason and a fix for now after playing around with everything in case anyone else runs into it: I went to the BetterEnd config and turned off Custom Sky and Fog Density. It seems these options cause conflict with the custom sky added from Sildurs.

**Comment by Sildurs-shaders** [comment]
Vibrant shaders have an option in the ingame settings to render the default skybox, not sure if that fixes the issue though.

**Comment by JAVIxcr** [comment]
Hello, this is happening to me too. The mod Better Forge is the one that is causing this issue.
Here is the link of the mod: https://www.curseforge.com/minecraft/mc-mods/betterend-forge-port
Minecraft Version: 1.16.5
Forge: 36.2.39

It solves with the mod config, turning off the custom sky
It is ok when you start the game and in the Dragon Area.
![Captura de pantalla 2023-02-01 013736](https://user-images.githubusercontent.com/124131949/215981014-350f1910-a63f-47f1-9ac3-ba57d2018cf2.png)

But when you explore it is like this:
![Captura de pantalla 2023-02-01 013840](https://user-images.githubusercontent.com/124131949/215981139-2a0228ec-d74f-4576-9b1a-5c24d9548f20.png)

And it goes worse in other areas, including placing blocks:
![Captura de pantalla 2023-02-01 013907](https://user-images.githubusercontent.com/124131949/215981217-29ae1ab6-d65f-4b9f-b6ae-f5c5b35d7683.png)
Here is the same frame but with other shader (as it should be):
![Captura de pantalla 2023-02-01 013934](https://user-images.githubusercontent.com/124131949/215981348-608d9483-58e5-4b55-9fba-f95c6c0ce6fb.png)

I just add this to help in a better solution :)

Thank you very much
