### ISSUE TITLE
Your ad network is causing redirects to malicious sites

### ISSUE THREAD

**Issue by nadiaholmquist** [Sildurs-shaders/sildurs-shaders.github.io#254]
I was trying to download your shaders, but clicking on links on your site seems to have a random chance of redirecting to different websites. Some of them the usual sketchy "hot singles in your area" type of site, and others, and far worse serving malicious files to the user.

Instead of the download, I got redirected to a site that downloaded `PlayerSetup.dmg` (hey Apple how about showing the filename of what you're downloading in Safari so you can notice you're getting the wrong thing *before* saving it to disk?) which I obviously didn't run, but that would have installed adware.

Please remove the script from your site ASAP before anyone actually falls for one of these malware links and gets their system infected.

**Comment by Sildurs-shaders** [comment]
This and other issues have been forwared to the advertisement company and should be filtered out by now.
