### ISSUE TITLE
Issues with shading and textures

### ISSUE THREAD

**Issue by Ind1g0146** [Sildurs-shaders/sildurs-shaders.github.io#255]
Hi!

Im experiencing some issues when using Sildur's Vibrant Shaders v1.41 Lite. Im using it on 1.19.2 with forge 43.1.7 and optifine HD U H9. 

First of all, there seems to be some issue with rendering shadows in darker areas, or just shadows in general. In this photo, Im in a dark strip mine however there is light shining through from the walls despite the fact that there are no light sources there. 

![2022-11-25_18 58 30](https://user-images.githubusercontent.com/118198794/204013499-d1d8751b-e25c-471e-a15f-130593d67d02.png)

In the next photos, there seems to be an issue with the textures when using shaders. I've only encountered this issue after turning shaders off and then on again and when i exit settings, the world looks like this. I have no idea how to fix this issue.

![2022-11-25_19 03 52](https://user-images.githubusercontent.com/118198794/204013972-78fa67fe-60f0-4950-80ab-1a9080d3519f.png)

![2022-11-25_19 05 14](https://user-images.githubusercontent.com/118198794/204014066-9bc44a83-3561-4b48-990e-243bf653617f.png)

This also seems to happen no matter what environment I'm in.

![2022-11-25_19 05 45](https://user-images.githubusercontent.com/118198794/204014127-7c089569-8ae4-4c8c-8d36-06499090bc14.png)

If you have any idea on how to fix this it would be much appreciated.

Thanks for reading!

Edit: The second issue seems to also happen when using other shaders like BSL or Complementary so it might be an issue with forge or optifine?

**Comment by Sildurs-shaders** [comment]
The first issue is just the "in a lowlight area" hack not triggering correctly or fast enough, because that's what it is, disabling the outside shading based on the lightlevel around the characters to prevent this. Not sure if it can be improved much more. The other issues seem to be mod issues yeah, try updating your gpu drivers to be sure though.
