### ISSUE TITLE
Is there any way to disable clouds?

### ISSUE THREAD

**Issue by eldeiibid** [Sildurs-shaders/sildurs-shaders.github.io#257]
Clouds will are always enabled along the shader even if they are disabled in rubidium/optifine options and there' no option to disable them in-game. Is there any way to disable them via options txt file or have you got any plans to add a "enable clouds" option in-game?
Thanks.

**Comment by Sildurs-shaders** [comment]
That should be fixed in v1.141 which is already out now for quite some time.
