### ISSUE TITLE
Skyline Blur

### ISSUE THREAD

**Issue by yuri0r** [Sildurs-shaders/sildurs-shaders.github.io#26]
Just asking if this is intentional and if it would be possible to disable this effect.
I mean the blur effect that seems to be applied to some stuff above the horizon and/or in front of the skybox.

<details>

the upper half of glass sprites (with skybox as the backdrop) seem blurred 
![2019-10-09_18 18 32](https://user-images.githubusercontent.com/9966894/66500471-df73b280-eac1-11e9-8312-2154012d3e7b.png)

</details>

i noticed it here 

<details>

(blur arround the ballon (from immersive Engenering))
![2019-10-09_18 15 33](https://user-images.githubusercontent.com/9966894/66500999-de8f5080-eac2-11e9-8fb6-320fdccf95cf.png)

</details>

my guess is that it was meant to make the stars sparkly(??) looking

<details>

kinda like in this picture
![2019-10-09_18 20 44](https://user-images.githubusercontent.com/9966894/66501109-0f6f8580-eac3-11e9-9e10-aa1743ccfc78.png)
as the sparkle effect is basically gone when zoomed into the skybox via optifine
![2019-10-09_18 20 12](https://user-images.githubusercontent.com/9966894/66501151-257d4600-eac3-11e9-94ac-d8ad94e539c6.png)

</details>

also I'd generally prefer the stars to be dots and not sparkles but that's just personal taste. also sorry for any typos and bad wording/phrasing Englisch ain't my native Language

**Comment by Sildurs-shaders** [comment]
That's caused by cloudsblur found in the sky and lighting section, it helps smoothing out the volumetric clouds without much of a performance hit. But you can disable it.

**Comment by yuri0r** [comment]
Interesting so sparkly stars are just a byproduct :D 
thank  you for the hint :)
