### ISSUE TITLE
[vibrant 1.50] bloom moves into camera movement direction

### ISSUE THREAD

**Issue by fayer3** [Sildurs-shaders/sildurs-shaders.github.io#262]
when moving the camera/walking side to side, the bloom moves in front of the objects

camera moved to the right here:
![grafik](https://user-images.githubusercontent.com/8282299/212909563-72a7df65-febc-4694-835e-b2edf12e4ef4.png)

**Comment by Sildurs-shaders** [comment]
Nvidia drivers caused a bunch of glitches but this might be fixed in the latest drivers, reopen if it's not.

**Comment by fayer3** [comment]
don't think that is a driver issue, also still happens with 536
the issue more likely is that you use the previous frame for the bloom, without re projecting it
also doesn't look like I can reopen this

**Comment by fayer3** [comment]
if I set it to use colortex3, instead of colortex7, the movement is gone.
it just flickers then because it's the jittered TAA frame

**Comment by Sildurs-shaders** [comment]
The framerate on my RTX 4070 was so high that I couldn't really reproduce this, capping the game at 20 fps makes it much more apparent, I'll look into it.

**Comment by SildurFX** [comment]
Fixed in upcoming vibrant shaders v2.0
