### ISSUE TITLE
Strange cloud rendering

### ISSUE THREAD

**Issue by Cha0sPudd1ng** [Sildurs-shaders/sildurs-shaders.github.io#266]
The clouds appear weird when you use the Enhanced Default shaderpack with the extended clouds mod.

![2023-01-27_05 43 06](https://user-images.githubusercontent.com/1367047/215328759-e0219de3-c910-407e-b831-41a74bc62f9e.png)

[Fabric 1.19.2 (0.14.12)](https://fabricmc.net)
[fabric-api-0.72.0+1.19.2](https://www.curseforge.com/minecraft/mc-mods/fabric-api)
[extendedclouds-1.2.0](https://www.curseforge.com/minecraft/mc-mods/extended-clouds)
[optifabric-1.13.16](https://www.curseforge.com/minecraft/mc-mods/optifabric)
[OptiFine_1.19.2_HD_U_I1](https://optifine.net)
[Sildur's+Enhanced+Default+v1.15+Fancy](https://www.curseforge.com/minecraft/customization/sildurs-enhanced-default)

**Comment by Sildurs-shaders** [comment]
Default cloud rendering in shaders is a bit tricky, if this is caused by a mod there's not much I can do about it, maybe it works better with iris though.
