### ISSUE TITLE
[Suggestion] Add a fog in the morning

### ISSUE THREAD

**Issue by A2va** [Sildurs-shaders/sildurs-shaders.github.io#27]
This shader (https://www.planetminecraft.com/mod/voyager-shader-beta/) adds a fog in the morning can you also do it on the Sildur's Vibrant Shaders ?
An option could be used to adjust its density or activation.
Thank you for this beautiful shaders

**Comment by Sildurs-shaders** [comment]
Fog density based on daytime might be possible

**Comment by Sildurs-shaders** [comment]
Dynamic fog density based on world time is going to be supported in the upcoming update. (v1.26)
