### ISSUE TITLE
Block breaking sprite transparency broke

### ISSUE THREAD

**Issue by MaikuDaelon** [Sildurs-shaders/sildurs-shaders.github.io#279]
Whenever i break a block, the sprites for breaking don't have any transparency and are pure black. I tried changing some settings to try and fix the problem myself but didn't find any solution for that. Please help!
![image](https://user-images.githubusercontent.com/75703180/222279826-1d2f8e62-1fff-4bb0-8e10-0d55b2e667cf.png)

**Comment by Sildurs-shaders** [comment]
Optifine or iris? Iris works better, closing this for now but feel free to reopen if it still happens.

**Comment by kevinwchang** [comment]
I'm also currently seeing this. Using:

Sildur's+Enhanced+Default+v1.16+Fancy.zip
iris-mc1.20.2-1.6.10.jar
sodium-fabric-mc1.20.2-0.5.3.jar

Let me know if any other info would be helpful. 

It doesn't seem to happen with your Vibrant shaders (Sildur's+Vibrant+Shaders+v1.51+Extreme-VL.zip) so something seems to be different in Enhanced Default that causes the problem.

If anyone *doesn't* have this problem, it'd be interesting to hear about your setup to try to figure out what's different.

![image](https://github.com/Sildurs-shaders/sildurs-shaders.github.io/assets/2257726/1a88fb8c-907d-477d-8cc2-93f59b67a81d)

**Comment by SMN47** [comment]
I have a similar issue while using Sildur's Vibrant Shaders v1.51 Medium
Block breaking texture appears to be exposed to excessive light, but also looks co
![2872_javaw_21-19-47](https://github.com/Sildurs-shaders/sildurs-shaders.github.io/assets/11785385/2e2911a1-de08-4794-9857-8a3253bd0f45)
mpletely black while I look at it from some angle
![2873_javaw_21-19-58](https://github.com/Sildurs-shaders/sildurs-shaders.github.io/assets/11785385/fc08696d-489b-4351-9fac-a4f54a3bd613)

3rd screenshot made with Sildur's Enhanced Default v1.16 Fancy
![2874_javaw_21-24-13](https://github.com/Sildurs-shaders/sildurs-shaders.github.io/assets/11785385/4406d43c-aff2-43e9-a0c1-81cd85560c28)

sodium-fabric-0.5.8+mc1.20.1
iris-1.7.0+mc1.20.1

**Comment by viiuan** [comment]
i am also having the brightness issue
