### ISSUE TITLE
[1.50-Extreme-VL] Turning off shadows disables all shaders, not just shadows.

### ISSUE THREAD

**Issue by CocaineJohnsson** [Sildurs-shaders/sildurs-shaders.github.io#282]
![2023-03-19_13 47 38](https://user-images.githubusercontent.com/53689060/226176332-ed9970c5-700d-470f-b3f3-2836216f04e0.png)

![2023-03-19_13 47 44](https://user-images.githubusercontent.com/53689060/226176214-bf84ca36-938f-4ac8-9a69-d0cad978e1f7.png)

Most notable on volumetric lighting and clouds vanishing, but also AO et. al.

**Comment by Fsxnerd** [comment]
I also have this issue. Trying to diagnose why entities (cows, floating blocks, etc) become invisible when using the shader, but not when all shaders are turned off

**Comment by Sildurs-shaders** [comment]
Fixed in upcoming version.
