### ISSUE TITLE
Rain Goes Through Solid Blocks When Looking Up

### ISSUE THREAD

**Issue by BMK2** [Sildurs-shaders/sildurs-shaders.github.io#284]
When I'm inside and it is raining, I noticed water goes through solid blocks. I'm running Minecraft 1.19.2 and the Enigmatica 9 1.5.0 modpack. For the shader, I'm running your Extreme Vibrant version. 
![image](https://user-images.githubusercontent.com/5030972/227590711-bc3fa4cd-c135-41fa-bbdd-e0735f09e9ce.png)

**Comment by Sildurs-shaders** [comment]
Does this happen without mods aswell? Closing this for now but feel free to reopen if it still happens with just iris/optifine.
