### ISSUE TITLE
[1.14.4][v1.24 - High] Game crashing with Shaders

### ISSUE THREAD

**Issue by jagyCZ** [Sildurs-shaders/sildurs-shaders.github.io#29]
Hey, my game is crashing after some time of playing with your shaders, i have 2 other mods installed - Voxel map and JEI. My game is able to run at 70 - 80 fps most of the time so i think it's not fault of my PC. Down below is short error code from MC console, full report is available [here](https://www.dropbox.com/s/jkvomfng9eau20r/hs_err_pid6884.log?dl=1)

14:44:32.401
EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00000000032a08b7, pid=6884, tid=7420
14:44:32.401

14:44:32.401
JRE version: Java(TM) SE Runtime Environment (8.0_51-b16) (build 1.8.0_51-b16)
14:44:32.401
Java VM: Java HotSpot(TM) 64-Bit Server VM (25.51-b03 mixed mode windows-amd64 compressed oops)
14:44:32.401
Problematic frame:
14:44:32.401
J 3390 C1 java.util.AbstractList.subList(II)Ljava/util/List; (31 bytes) @ 0x00000000032a08b7 [0x00000000032a0820+0x97]
14:44:32.401

14:44:32.401
Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
14:44:32.401

14:44:32.401
An error report file with more information is saved as:
14:44:32.401
E:\Users\xyz\xyz\xyz\xyz\xyz\1.14\hs_err_pid6884.log
14:44:32.417

14:44:32.417
If you would like to submit a bug report, please visit:
14:44:32.417
  http://bugreport.java.com/bugreport/crash.jsp
14:44:32.417

14:44:32.418
AL lib: (EE) alc_cleanup: 1 device not closed
14:44:32.931
Process crashed with exit code 1

**Comment by Sildurs-shaders** [comment]
Shaders shouldn't crash the game, this might be a mod conflict issue with optifine, you should checkout the optifine discord for more help. https://discord.gg/Eut4tgm
