### ISSUE TITLE
[Basically a PR] Rain Drops being disabled breaks the entire shader

### ISSUE THREAD

**Issue by downloadpizza** [Sildurs-shaders/sildurs-shaders.github.io#290]
In the `final.vsh` the two variables
```vsh
uniform ivec2 eyeBrightnessSmooth;
uniform float rainStrength;
```
should not be in the `Rain_Drops` ifdef. Instead they should be global scope or at least in a block that exists if either bloom or rain is active.

Them being in there makes compilation fail when disabling rain_drops without also disabling bloom.

**Comment by Spaceb0i** [comment]
Is removing those two lines and recompressing the file supposed to fix the compilation error? When I tried removing those two lines, it would fail to compile regardless of whether bloom or raindrops were on or off

**Comment by downloadpizza** [comment]
> Is removing those two lines and recompressing the file supposed to fix the compilation error? When I tried removing those two lines, it would fail to compile regardless of whether bloom or raindrops were on or off

You need to move them to a valid scope. Just removing them breaks everything of course. Move them outside to above the `#ifdef`

**Comment by downloadpizza** [comment]
Unless im blind 1.51 still does not have this fixed. Its not an issue for me since I can just fix it myself, but maybe others would benefit from just hotfixing by moving the two lines real quick in the release on sildurs-shaders.github.io

**Comment by C0nnor64** [comment]
> Unless im blind 1.51 still does not have this fixed. Its not an issue for me since I can just fix it myself, but maybe others would benefit from just hotfixing by moving the two lines real quick in the release on sildurs-shaders.github.io

Can confirm, still not fixed.

**Comment by Sildurs-shaders** [comment]
fixed in upcoming version.
