### ISSUE TITLE
Black Box Around Sun/Moon and Rain Through Blocks

### ISSUE THREAD

**Issue by cyruspianopaws** [Sildurs-shaders/sildurs-shaders.github.io#292]
![2023-04-13_22 23 40](https://user-images.githubusercontent.com/130796765/232146786-fb8276fe-5d4b-4828-b01d-cd9fe852b84a.png)
Whenever I load into my modded server (around 100 mods) I get this issue with both the sun and the moon. I saw it mentioned on here that the rain is also buggy and can be seen through blocks for some reason. Also, the rain seems to be vanilla rain despite having the shader on and running. My friends are having the same issues on every version of the shaders (Lite-Extreme, although we use High). We have also tried tweaking a ton of the shader options to no avail. The only fix is to turn off the sun and the moon and turn off/ignore the rain which is tragic, as the moon/rain are some of the best parts of this shader!

These shaders work fine on a lightly modded server. I've check all the mods in my modpack and can't find what would be causing the issue. If you want to check it yourself, this is the modpack: [Our Server Pack.zip](https://github.com/Sildurs-shaders/sildurs-shaders.github.io/files/11236725/Our.Server.Pack.zip)

It is running on MC 1.19.2, Forge 43.2.0 and Optifine 1.19.2 HD U I1 w/ the latest version of Sildur's Vibrant Shaders (1.50)

My Specs are:
AMD Ryzen 5 3600 6-Core Processor, 3593 Mhz, 6 Core(s), 12 Logical Processor(s)
Nvidia GTX 2060 Super
Installed Physical Memory (RAM) 15.9 GB

Any help would be super appreciated. I do not want to have to use a different shaderpack, as I adore this one too much. Every other one me and my friends have tried, we simply don't like nearly as much.

**Comment by Sildurs-shaders** [comment]
Have you tried Iris instead of optifine? I think it can also be used as a forge mod. If you are using astral sorcery there was a shader specific setting that needed to be changed, check their mod page for that. Closing this since there's not much else I can do about it, enhanced default works better with mods because it's rendering system is closer to vanilla.
