### ISSUE TITLE
[MC 1.19.2 / Vibrant 1.50 / Iris] Horses Are Translucent

### ISSUE THREAD

**Issue by OrniiDiien** [Sildurs-shaders/sildurs-shaders.github.io#296]
![2023-05-11_21 40 58](https://github.com/Sildurs-shaders/sildurs-shaders.github.io/assets/63260365/7efd66ce-9551-4cbf-b9d2-94884f23d888)
With version 1.50 of Vibrant shaders. Playing on MC 1.19.2 with Fabric+Iris.
Occurs only to these horses with the **black speckled pattern** on them (but strangely not horses with the "black", "gray", or "white" texture- maybe because of lack of colour saturation on these textures?); I think this is because of transparency on the texture itself. _This is a vanilla texture_, found at `assets\minecraft\textures\entity\horse\horse_markings_blackdots.png`.
Translucence only occurs when shader is on. I'm 100% sure it's related to this vanilla texture and not to any mod or resource pack.

**Comment by Sildurs-shaders** [comment]
Vibrant shaders is an old pack an has some issues with transparency that can't really be fixed without a rewrite from scratch, so I'll close this for now but thanks for the bug report.
