### ISSUE TITLE
Textures glitching optifine-forge

### ISSUE THREAD

**Issue by xLastMarloKx** [Sildurs-shaders/sildurs-shaders.github.io#297]
Hi, every time i turn on this shaders, the textures turn weird, searched a lot to try to solve this issue but i dont undertand why this is happening . 

On iris it works fine , but i want to use it in forge ( like i always did ) , forge version 43.2.11 optifine version OptiFine_1.19.2_HD_U_I1 ( with others the game breaks when loading ) tryed with sildurs 1.50-1.41-1.32 & 1.31 and it always looks like this : 
![minecraftshaders](https://github.com/Sildurs-shaders/sildurs-shaders.github.io/assets/84780392/e26145be-1585-4bc5-b696-ca914b534668)

**Comment by CoolDogGX** [comment]
I had the same problem :(

**Comment by Sildurs-shaders** [comment]
If iris works just fine this is an optifine bug, also I'm pretty sure iris can be used with forge.
