### ISSUE TITLE
Black sky with sildur vibrant shader lite ; medium

### ISSUE THREAD

**Issue by YoucefKB01** [Sildurs-shaders/sildurs-shaders.github.io#300]
When i use sildurs vibrant shader ; a black sky appears ; i try to turn off the sky ; i didn't see any result ; i try turn off and turn in some settings and no result ; i do know where is the problème ; any one can help me ?
![Uploading IMG20230530115450.jpg…]()

**Comment by Sildurs-shaders** [comment]
Your image doesn't work like that, I'm closing this for now.
