### ISSUE TITLE
hyperlinks lead to... questionable websites.

### ISSUE THREAD

**Issue by devcey** [Sildurs-shaders/sildurs-shaders.github.io#302]
hey; just been wanting to install the shaders... however all the hyperlinks in the website have been leading to NSFW websites (which for quite obvious reasons I will not link down in there)... I doubt this is the expected behaviour and I didn't see any issues on the github repo, so I thought I'd just report that... kind of disturbing to see.

**Comment by StereoMadnessss** [comment]
YES I know this, if you click anywhere it results in you going to malicious websites, this should be fixed immediately

**Comment by StereoMadnessss** [comment]
Use CurseForge as the shaders are being posted there

**Comment by StereoMadnessss** [comment]
in 2021 it did not have this problem

**Comment by Sildurs-shaders** [comment]
Forwarded this to my ad network, they host the ads, sometimes bad ones slip through I guess, sorry about that.

**Comment by StereoMadnessss** [comment]
Clicking anywhere still results in being redirected to sketchy websites
