### ISSUE TITLE
Unable to download shader, so how do I get it?

### ISSUE THREAD

**Issue by DaddyPoppe** [Sildurs-shaders/sildurs-shaders.github.io#305]
I went to this site https://sildurs-shaders.github.io/downloads/
and every time I click on the download link (Sildur's Vibrant shaders v1.51 High) I am sent to a harmful page.
The same goes for the other download links
I even disabled the security and was sent to a very suspicious page, where there was no Shader download.

So how or where can I download the shader?

**Comment by Sildurs-shaders** [comment]
https://legacy.curseforge.com/minecraft/shaders/sildurs-vibrant-shaders
