### ISSUE TITLE
Ambient Occulusion Issue in Extreme VL v.1.25

### ISSUE THREAD

**Issue by Arturitu12** [Sildurs-shaders/sildurs-shaders.github.io#31]
I've got an issue when i downloaded v.1.25. Lights on blocks around 40 blocks far from me, starts to blinking a little, it's most visible in night. It's annoying most on quartz - my favorite block. I tried to off and on some options and i found that blinking come in when Ambient Occulusion is ON. When I change AO amount it's comes stronger on higher amount but still visible and annoying on 1.0. On versions before 1.25 it's don't happening. Can you tell me what 
it can cause, maybe an optifine option - I don't know. 

It's hard to show on gif so I uploaded to non public video on YT link below:
https://youtu.be/G3RZxi-yfwI

**Comment by Sildurs-shaders** [comment]
Fixed in the upcoming version. (v1.26)

**Comment by Arturitu12** [comment]
> Fixed in the upcoming version. (v1.26)

Thx, you doing a good job :)
