### ISSUE TITLE
[Enhanced Default 1.16] Weird line shadow on armor

### ISSUE THREAD

**Issue by najis-poop** [Sildurs-shaders/sildurs-shaders.github.io#310]
If you go close to player with armor when there is light on them, you will see this weird line shadow on the armor

![image](https://github.com/Sildurs-shaders/sildurs-shaders.github.io/assets/84977144/a77da762-bd10-43d9-9cf5-5911cda84f99)

**Comment by Sildurs-shaders** [comment]
Shadow acne, can be fixed my increasing shadow resolution or lowering shadow distance.
