### ISSUE TITLE
Shader failed to load after disabling rain drops on camera

### ISSUE THREAD

**Issue by RuafuMan-Obs** [Sildurs-shaders/sildurs-shaders.github.io#314]
final.vsh: final.vsh: 0(47) : error C1503: undefined variable "eyeBrightnessSmooth"
0(52) : error C1503: undefined variable "rainStrength"

version v1.51 Ex+VL

**Comment by TromboneFreak** [comment]
My error is

"[Shaders] Error: Invalid program "final" and things look.. terrible.

![2023-11-27_15 35 14](https://github.com/Sildurs-shaders/sildurs-shaders.github.io/assets/37919916/3c590e8d-ee3a-4bf1-b5c2-f441bd0f946d)
![2023-11-27_15 35 03](https://github.com/Sildurs-shaders/sildurs-shaders.github.io/assets/37919916/43143b6f-8d02-4e85-a1e4-b0850cc004c4)
