### ISSUE TITLE
Enhanced Default weird artifacts on tools and blocks

### ISSUE THREAD

**Issue by SirWindfield** [Sildurs-shaders/sildurs-shaders.github.io#32]
Just turned the shaderpack on and I get weird artifacts showing on the ground and on some items. Diamond tools for example have a weird reflection on them, not sure if this is intended or not. Applies to all metallic like tools from modded or vanilla.

The blocks have this strip-y texture on them, everywhere.
![2019-11-23_12 34 28](https://user-images.githubusercontent.com/5113257/69478048-f5c59b80-0ded-11ea-9b8e-934ebe164483.png)

The chest and tank below for example have weird artifacts inside of them:
![2019-11-23_12 37 49](https://user-images.githubusercontent.com/5113257/69478055-14c42d80-0dee-11ea-84f7-93fc26533b59.png)

The bed here has some artifacts too. They disappear if I am near enough to the bed itself.
![2019-11-23_12 38 53](https://user-images.githubusercontent.com/5113257/69478067-3a513700-0dee-11ea-8327-e0b97369300a.png)

**Comment by Sildurs-shaders** [comment]
Increasing the shadow resolution or reducing the shadow render distance should help with the "stripy texture". Not sure about the artifacts, but it might be fixed in the upcoming version since I did some optimizations.

**Comment by Sildurs-shaders** [comment]
Closed this for now, feel free to reply if this is still an issue.
