### ISSUE TITLE
Respect gamma overrides

### ISSUE THREAD

**Issue by blaumeise20** [Sildurs-shaders/sildurs-shaders.github.io#320]
I'm using Tweakeroo with the `gammaOverride` option, which works fine without shaders. However it is not respected with this shader (lite variant), and there is no visible change when enabling gamma override.

**Comment by Sildurs-shaders** [comment]
Vibrant shaders uses it's own lighting system, you can tweak the minimum light in the ingame options -> emissive light.
Use enhanced default or basic shaders if you need proper mod support.
