### ISSUE TITLE
Cell shading not working in nether

### ISSUE THREAD

**Issue by UniqueUsernameGoesHere** [Sildurs-shaders/sildurs-shaders.github.io#321]
Hi there, I am not a coder, just someone who uses the shaders and loves the cell shading option! I am disappointed that it doesn't seem to carry over into the nether and wanted to raise this issue, apologies if this is already known or if this is not the correct channel for doing so.

**Comment by Sildurs-shaders** [comment]
Fixed in upcoming version.
