### ISSUE TITLE
Random Black panel appearing.

### ISSUE THREAD

**Issue by IshraqNotFound** [Sildurs-shaders/sildurs-shaders.github.io#322]
![2024-01-25_15 00 11](https://github.com/Sildurs-shaders/sildurs-shaders.github.io/assets/153723262/db45bf35-cf45-4640-8d69-9328ce628a08)
![2024-01-25_14 59 10](https://github.com/Sildurs-shaders/sildurs-shaders.github.io/assets/153723262/33270245-2187-434b-b83e-dd7e1fdac8e4)
idk why it happens.
I don't use any GPU, I use intel HD 2500 grapics to render. &
I have 3995mb of allocated memory.

**Comment by Sildurs-shaders** [comment]
Looks more like a chunk loading issue or maybe running out of vram. Make sure your drivers are up to date. This is the latest one for your intel hd 2500:
https://www.intel.com/content/www/us/en/download/18606/29969/intel-graphics-driver-for-windows-15-33.html
