### ISSUE TITLE
Modpack Usage Request

### ISSUE THREAD

**Issue by WorldOfTonys** [Sildurs-shaders/sildurs-shaders.github.io#323]
Hello, I have a question.
Could I use the Sildurs Enhanced Default Shaders for my own modpack on Modrinth? Of course I will make sure to link back to your shaderpack page.

**Comment by Sildurs-shaders** [comment]
Thanks for asking but including it in a modpack is not allowed as it might cause issues on certain hardware and become outdated. Also my shaders are not available on modrinth so having a modpack with it included on that website is a bit weird.
