### ISSUE TITLE
Incompatibility with Streams mod in 1.12.2

### ISSUE THREAD

**Issue by XvaleX10** [Sildurs-shaders/sildurs-shaders.github.io#324]
![2024-02-05_16 05 52](https://github.com/Sildurs-shaders/sildurs-shaders.github.io/assets/129081719/c40ea5a8-22c2-4842-8bb1-c0ca6b7cd718)
![2024-02-05_16 06 03](https://github.com/Sildurs-shaders/sildurs-shaders.github.io/assets/129081719/4d2553ee-1377-4375-801f-1d03bfb26039)
stream water is not rendered correctly

**Comment by Sildurs-shaders** [comment]
You have to open up block.properties in the shaderpack zip file and edit it with any text editor. Then add the streams water IDs to the existing water ids in there. You might have to use the modname first, someting like streams:flowing_water or whatever it's called in that mod.
