### ISSUE TITLE
hardcore darkness not working

### ISSUE THREAD

**Issue by PhantomAshes** [Sildurs-shaders/sildurs-shaders.github.io#326]
im on 1.12.2, ive loaded lite, extreme and extreme VL shaders and all of them seem to override hardcore darkness and prevent it from working.

**Comment by Sildurs-shaders** [comment]
Vibrant shaders uses a custom lighting system, enhanced default and basic shaders work better with mods. But vibrant shaders also provides a native way to make it darker, kinda like said mod. Go in to your ingame shader options -> emissive light and lower minimum light to 0.001.
