### ISSUE TITLE
Transparent blocks inherit the distance of the background for blurring

### ISSUE THREAD

**Issue by CCheukKa** [Sildurs-shaders/sildurs-shaders.github.io#328]
When distance blur is enabled, transparent blocks inherit the distance of their background and blur based on the distance of whatever is showing through instead of their own distance.

See here the glass scratches blurs as though they are very far away.
![image](https://github.com/Sildurs-shaders/sildurs-shaders.github.io/assets/38432731/c5cf5ed6-c556-4477-b19e-9f14ed793430)

Here I decreased the blur distance way down to exaggerate the effect.
![image](https://github.com/Sildurs-shaders/sildurs-shaders.github.io/assets/38432731/016b9255-6688-4d50-9ec2-0a1d45bfad06)

**Comment by Sildurs-shaders** [comment]
This is based on a workaround I had to implement because of broken amd drivers. It's fine on nvidia and intel cards. I'm not sure if said workaround is still needed to be honest, this was implemented years ago.
