### ISSUE TITLE
[1.7.10] Optifine_1.7.10_HD_U_E7 - Crash after closing game with initial shader pack load

### ISSUE THREAD

**Issue by syndicate25** [Sildurs-shaders/sildurs-shaders.github.io#331]
When I load the game without the shaderpack, it's fine.  I can then select it and use it, and it looks great.  I turn off AA because I am aware of the known problem there, but everything else is fine....Until I try to relaunch the game.

https://pastebin.com/fpmvUkch

In order to load my game again, I have to remove the shaderpack from the shaderpacks directory and then launch it again.

**Comment by Sildurs-shaders** [comment]
Should be fixed in upcoming version, taa will be auto disabled if version 1.7.10 is detected.
