### ISSUE TITLE
Vibrant Shader v1.51 crash

### ISSUE THREAD

**Issue by Blackmadman** [Sildurs-shaders/sildurs-shaders.github.io#332]
If you try to turn off the raindrops on screen, the whole shader stops working and this message appears:
Any way to fix this?

final.vsh: final.vsh: 0(47) : error C1503: undefined variable "eyeBrightnessSmooth"
0(52) : error C1503: undefined variable "rainStrength"

**Comment by Sildurs-shaders** [comment]
Fixed in upcoming version.
