### ISSUE TITLE
Shadows artifacts in the Nether and End on Enhanced shaders

### ISSUE THREAD

**Issue by Asertus1** [Sildurs-shaders/sildurs-shaders.github.io#334]
I have some artifacts in the nether and the end, that disappear when disabling shadows in shaders settings. No problem using Vibrant shaders.

I am using Iris and Sodium as Fabric mods.

![2024-06-17_23 17 07](https://github.com/Sildurs-shaders/sildurs-shaders.github.io/assets/88512882/3fb7810c-66aa-4ea3-8f45-2901d44dc595)

**Comment by Mjddcreator** [comment]
same here (iris and sodium as fabric mods)
![image](https://github.com/Sildurs-shaders/sildurs-shaders.github.io/assets/173106678/68bc0a81-6a5b-4243-8411-405907e1cba4)

**Comment by Sildurs-shaders** [comment]
Can confirm but this only happens with iris for MC 1.21. Maybe that build is still a work in progress. 1.20.6 and below are fine.

**Comment by Sildurs-shaders** [comment]
Implemented a workaround even though this should be fixed in iris instead. Hotfix is live now.
