### ISSUE TITLE
[1.12.2] Crash on v1.261 Extreme-VL.

### ISSUE THREAD

**Issue by VanillaChan6571** [Sildurs-shaders/sildurs-shaders.github.io#36]
[crash-2019-11-30_15.48.24-client.txt](https://github.com/Sildurs-shaders/sildurs-shaders.github.io/files/3907664/crash-2019-11-30_15.48.24-client.txt)

Crashes Each time trying load these shaders. Default Shaders load fine.

**Comment by Sildurs-shaders** [comment]
Try deleting shaders.properties in the shaderpack zip file, this will break the lightning fix. There an optifine / forge bug, causing this.

**Comment by xXDarkNovaXx** [comment]
I didn't want to open a new post for this now
What does the entity.properties
And why wasn't the bug fixed by Optifine/Forge - the bug has been known for quite some time?

**Comment by Sildurs-shaders** [comment]
This is fixed in the current preview version for 1.12.2 F6_pre1. It's used to map entities to ids so that I can use them in my code.
