### ISSUE TITLE
Weird black circles on the ground

### ISSUE THREAD

**Issue by shintol** [Sildurs-shaders/sildurs-shaders.github.io#38]
I'm using the "Sildur's Vibrant shaders v1.262 High" version and I'm getting weird circles on the ground, even in void dimensions. They move with me and act like there's something between them and the sun. More appear as it gets darker. I'm running this on FTB Revelation modpack if that helps with knowing what other mods there are. 

![shaders](https://user-images.githubusercontent.com/28391112/73518317-f2412880-43cb-11ea-904b-6c0585f56a95.png)

I've tried playing around with most of the options in the shader options menu but nothing seems to get rid of them.

**Comment by Tonas1997** [comment]
Can confirm, also getting those.

**Comment by Sildurs-shaders** [comment]
Fixed in upcoming version.
