### ISSUE TITLE
Texture Issue

### ISSUE THREAD

**Issue by carlucci9660** [Sildurs-shaders/sildurs-shaders.github.io#40]
Love your work, thank you for your time and making me and others enjoy there game much more......One issue id like to mention, having texture issues with Powah Mod for 1.14.4 >> see photo

I have also attached photos without your shader loaded and the lasers seem to work as intented. 

![2020-02-01_22 12 55](https://user-images.githubusercontent.com/31194015/73685224-cb1c7c80-4693-11ea-808e-6534b9dd6518.png)
![2020-02-01_22 12 58](https://user-images.githubusercontent.com/31194015/73685225-cb1c7c80-4693-11ea-8473-6d372ad23e61.png)
![2020-02-03_14 42 27](https://user-images.githubusercontent.com/31194015/73685226-cb1c7c80-4693-11ea-8d64-e10336cfc50d.png)
![2020-02-03_14 42 30](https://user-images.githubusercontent.com/31194015/73685227-cb1c7c80-4693-11ea-9586-a2f7b2dfec8d.png)

**Comment by Sildurs-shaders** [comment]
Not much I can do about mod support in vibrant shaders, might want to use enhanced default instead.
