### ISSUE TITLE
[1.15] No breaking block animation

### ISSUE THREAD

**Issue by LukasAppleFan** [Sildurs-shaders/sildurs-shaders.github.io#45]
## Description of Issue

When using Sildurs Vibrant Shaders and breaking blocks it shows no animation.

## Steps to Reproduce

1. Enable Sildurs Vibrant Shaders, tested with 1.27 and 1.262, in Extreme and Low
2. Breaking blocks

## OptiFine version

OptiFine 1.15.2 HD U G1 pre13

## Installation Method

With either OptiFine or Forge (using OptiForge).

## Screenshot (with F3 menu)

![2020-04-04_10 08 25](https://user-images.githubusercontent.com/41242166/78422041-c7d64a80-765c-11ea-9753-5cc058bf8e26.png)

## Additional Information

I've tested with other shaders, and it works fine.
Tested with and without a resource pack and it will always happen.

**Comment by Sildurs-shaders** [comment]
Are you sure it works with other shaders, did you try it on the latest optifine preview? It works fine in 1.14.4 and lower so this is marked as an optifine bug for me.

**Comment by LukasAppleFan** [comment]
After some testing... it only shows using other shaders, and I was using the latest preview.
Talking about OptiFine bugs, the block selector is not showing with shaders on on some worlds, but that happens with any shaders, so it's not Sildurs fault.

**Comment by LukasAppleFan** [comment]
You seemed to have closed the issue this sounds great 😉, hope you're having a good day.
