### ISSUE TITLE
[1.15.2] Flashing loading chunks & shadow strokes v1.27 Default and Light

### ISSUE THREAD

**Issue by Excaliburning** [Sildurs-shaders/sildurs-shaders.github.io#46]
Hello !

[Pictures are worth a thousand words.](https://imgur.com/a/mghx0qg)

As written in the descriptions, with Sildur's Default the chunks being loaded are flashing during sunset and moon rise. Does not happen with Sildur's Light.
However with Sildur's Light, during sunset some strange waves of shadow "strokes" can be seen, moving towards the sun.

Happens on Default & Lite v1.27.

Please, send me a life-boat !

**Comment by Sildurs-shaders** [comment]
The shadow stuff is due to low shadow res, so increasing that helps. Not sure about the enhanced default issue, does it happen in 1.14.4 aswell? If not it's an optifine bug

**Comment by Sildurs-shaders** [comment]
Closed this for now, if it's still an issue just reply again. As for shadow strokes, increasing shadow quality might help with that.
