### ISSUE TITLE
Textures / lighting glitch, making lot or everything purple

### ISSUE THREAD

**Issue by Mrcubix** [Sildurs-shaders/sildurs-shaders.github.io#49]
using latest 1.14.4 optifine version as well as latest sildur's version, problem appear in all version (from low to extreme VL), default option, i've reset video settings multiple times, still not fixed.
![2020-04-16_21 41 02](https://user-images.githubusercontent.com/39861216/79499949-ffb19a80-802b-11ea-851f-49852acf368d.png)
![2020-04-11_04 02 24](https://user-images.githubusercontent.com/39861216/79500017-148e2e00-802c-11ea-9c35-8b83e248b31e.png)

**Comment by Sildurs-shaders** [comment]
Check if it happens in 1.14.4 aswell, also try without any mods but optifine. Make sure gpu drivers are up to date

**Comment by Mrcubix** [comment]
added the fact, that, i'm in 1.14.4, it seem like this shader is incompatible with the latest 1.14.4 version of litematica, and cause this purple color on the first screenhsot

**Comment by slinkouswasalreadytaken** [comment]
something similar occasionally happened with blender's real time engine.
updated my mac and it works fine.

**Comment by Sildurs-shaders** [comment]
Mod or maybe driver issue, not much I can do about it, might be fixed in future versions due to rendering pipeline rewrites.
