### ISSUE TITLE
Suggestion: Shader templates

### ISSUE THREAD

**Issue by slinkouswasalreadytaken** [Sildurs-shaders/sildurs-shaders.github.io#51]
First up, I'd just like to say that your vibrant shaders are amazing. : )
Using a mac laptop, and the fact that I don't need to completely switch my computer to have graphics worth looking at is really kinda nice...

Anyway here's the suggestion:
A basic version of your vibrant shaders, with easy to understand parameters, comments on what the values do within the code, and other stuff that would help people trying to start out making shaders, or just coding in general! : )

**Comment by Sildurs-shaders** [comment]
Enhanced Default has pretty clear and somewhat documented code, but of course it can't be used as a base though, in case you want to release something.
