### ISSUE TITLE
[1.14.4] Enhanced Default Flickering Sunrise/Sunset

### ISSUE THREAD

**Issue by Bopler** [Sildurs-shaders/sildurs-shaders.github.io#52]
Video: https://streamable.com/fsk57j

Have had this flickering issue the past 2 versions of the shaders, basically during sunrise and sunset there is a flickering band radiating from the sun. The issue stays no matter what texture pack. Changing alternate sun angle also makes no difference. Disabling the sun entirely via optifine removes the band, but obviously I'd like to have a sun.

**Comment by Sildurs-shaders** [comment]
Are you running 1.15.2? Might be an optifine preview build bug

**Comment by Bopler** [comment]
> 
> 
> Are you running 1.15.2? Might be an optifine preview build bug

Nope! 1.14.4, newest stable optifine build

**Comment by Sildurs-shaders** [comment]
Hmm, did you try it with optifine only, as in no other mods.

**Comment by Sildurs-shaders** [comment]
Closed for now, feel free to respond / update your issue.
