### ISSUE TITLE
[1.15.2] Vibrant Shaders v1.27: Lightning Issues

### ISSUE THREAD

**Issue by RobbyCBennett** [Sildurs-shaders/sildurs-shaders.github.io#53]
I'm having all sorts of issues with lightning.

[Sometimes random entities flash, depending on your perspective](https://user-images.githubusercontent.com/22121365/82626271-a4337900-9ba4-11ea-8908-fd981d627f62.png)

[Sometimes lightning appears black at daytime](https://user-images.githubusercontent.com/22121365/82626277-a8f82d00-9ba4-11ea-87dc-6b0457d76949.png)

[Sometimes lightning appears red at night](https://user-images.githubusercontent.com/22121365/82626292-adbce100-9ba4-11ea-9ad4-e0df9c5e504a.png)

[Strange visual glitch when entities get struck by lightning near you](https://user-images.githubusercontent.com/22121365/82626296-b1506800-9ba4-11ea-83f2-5ad1d2790013.png)

[Usually lightning is invisible](https://user-images.githubusercontent.com/22121365/82626301-b44b5880-9ba4-11ea-88ae-21650b69e9f3.png)

**Comment by RobbyCBennett** [comment]
This only happens when I'm using this shader. Here is some bebugging info:
![image](https://user-images.githubusercontent.com/22121365/82626771-e0b3a480-9ba5-11ea-8372-f41c447dd6c6.png)

**Comment by Sildurs-shaders** [comment]
Update optifine and your gpu driver. Also optifine for 1.15.2 is still just preview builds. If you want to check if somethings a 1.15.2 optifine bug check if it happens in 1.14.4

**Comment by RobbyCBennett** [comment]
Okay. I updated my GPU driver and that didn't fix it. It's a 1.15.2 optifine bug, because it worked fine in 1.14.4

**Comment by RobbyCBennett** [comment]
It's an open issue on the optifine repo.

**Comment by Aidan-Lineberry** [comment]
could you reference it ?

**Comment by Aidan-Lineberry** [comment]
> It's an open issue on the optifine repo.

could you reference it ?

**Comment by RobbyCBennett** [comment]
https://github.com/sp614x/optifine/issues/2383
