### ISSUE TITLE
Vibrant Shaders: The moon is too bright

### ISSUE THREAD

**Issue by RobbyCBennett** [Sildurs-shaders/sildurs-shaders.github.io#54]
Feature Request:
The moon should automatically adjust brightness of the glow and the reflection of the moon in the water, according to the moon phase. The full moon should be the brightest and the new moon should be the darkest, with very little reflection in the water.

Feature Request:
It would be great to have an option to make the moon glow darker in general. This would adjust all of the phases of the moon to have less of a glow.

An example of the new moon being too bright in the sky and in the water reflection.
![image](https://user-images.githubusercontent.com/22121365/82632840-a272b100-9bb6-11ea-9338-0103186e759f.png)

**Comment by Aidan-Lineberry** [comment]
let's just have the moon brightness on a slider ?

i'd personally like moonlight to be brighter, but i can also see why you'd like it to be darker.

**Comment by Sildurs-shaders** [comment]
I think this is fine as is.
