### ISSUE TITLE
Feature Request: Reflections on normal glass

### ISSUE THREAD

**Issue by RobbyCBennett** [Sildurs-shaders/sildurs-shaders.github.io#55]
This is a great shader! It would be cool if the reflections I see on stained glass could be on normal glass too.

**Comment by Sildurs-shaders** [comment]
The issue with that is that normal glass has no proper texture to reflect off. Only a few pixels for the border and such. Still added the enhancement label and will keep this open, there's apparently a way to do it but I havent quite figured out how.
