### ISSUE TITLE
motionblur not working against sky

### ISSUE THREAD

**Issue by Aidan-Lineberry** [Sildurs-shaders/sildurs-shaders.github.io#57]
atts, issue seen on compass in bottom right
![2020-06-11_15 19 18](https://user-images.githubusercontent.com/21160455/84435930-3b19b100-abf8-11ea-88b9-30670e8ea637.png)

**Comment by Sildurs-shaders** [comment]
Hand and handheld items are only blurred on the edges, can't reproduce the against the sky thing.
