### ISSUE TITLE
Bloom glitch

### ISSUE THREAD

**Issue by RussellSB** [Sildurs-shaders/sildurs-shaders.github.io#58]
Bloom in 1.27 makes a weird lava texture overlay on the player when looking at lava. Especially visible in the Nether. This sometimes happens to torches too

**Comment by Sildurs-shaders** [comment]
Is optifine up to date, also what MC version? This shouldn't happen anymore.

**Comment by Sildurs-shaders** [comment]
Closed for now, feel free to respond if it still happens.

**Comment by RussellSB** [comment]
Apologies for the late reply. This was on 1.15.2 but it the updated version for 1.16 doesn't have this anymore. Thank you!
