### ISSUE TITLE
Adding edge of the world fog

### ISSUE THREAD

**Issue by impascal** [Sildurs-shaders/sildurs-shaders.github.io#59]
I love the shaderpack but because I can play only with low render distances (10-11) the atmosphere is kinda ruined when I see things rendering from nothing and it would be cool to have a edge of the world fog (similar to the one in vanilla). I've seen that  Complementary Shaders ([https://www.curseforge.com/minecraft/customization/complementary-shaders](url)) have this feature and I would like to ask if it can be added to Sildurs shaders.

**Comment by Sildurs-shaders** [comment]
Vibrant shaders has fog, you might need to tweak it in the ingame shader options. If you want vanilla fog enhanced default supports that.
