### ISSUE TITLE
Clouds are glitched in screenshots

### ISSUE THREAD

**Issue by Piipperi** [Sildurs-shaders/sildurs-shaders.github.io#6]
![Cloud Glitch](https://user-images.githubusercontent.com/29174220/62379979-cf36d880-b550-11e9-8c58-9671cddda118.png)

**Comment by Sildurs-shaders** [comment]
I think this only happens while playing in 4k.

**Comment by Piipperi** [comment]
> I think this only happens while playing in 4k.

Yeah but can you fix it?

**Comment by Sildurs-shaders** [comment]
Hmm, will see, not sure what causes it.

**Comment by Piipperi** [comment]
> Hmm, will see, not sure what causes it.

ok thx, if possible please let me know when/if you find a fix for it

**Comment by Sildurs-shaders** [comment]
To update on this, it seems to have something todo with the dithering not being able to handle this high of a resolution, not sure how to workaround that just yet.

**Comment by Sildurs-shaders** [comment]
Might be fixed in v1.25 due to several changes.
