### ISSUE TITLE
Feature Request: Option for better Screen Space Reflections at the edges of the screen

### ISSUE THREAD

**Issue by pfreundl** [Sildurs-shaders/sildurs-shaders.github.io#60]
Hi,

i really enjoy this shaderpack and would like to contribute this idea: would it be possible to internally render a wider FOV so you can get more information about the terrain beyond the edges of the screen so you can improve the screen space reflections there? It would probably cost quite a bit performance but make SSR look 100 times better at the edges of the screen (especially when you look at water reflections at dusk or dawn, since the high contrast between the dark reflected terrain and the bright reflection of the sun replacing it on the edges really emphasize it).

thanks, love your work :)

**Comment by Sildurs-shaders** [comment]
Vibrant shaders 2.0 (rework from scratch) might features better reflections.
