### ISSUE TITLE
Downloads are not from Github Releases

### ISSUE THREAD

**Issue by 8x13b** [Sildurs-shaders/sildurs-shaders.github.io#62]
You should make all the shaders be on github for faster downloads, and also no popunders from mediafire.

**Comment by slinkouswasalreadytaken** [comment]
This would be nice, but download links are how Slidur makes his/her money...

**Comment by EnderBro123** [comment]
Just put up a Patreon. Ezpz.

**Comment by NatoBoram** [comment]
That would require using GitHub to host the shaderspack, but it doesn't seems like it's open source.

**Comment by widget-** [comment]
In that case they shouldn't be using Github to host the website for it.
