### ISSUE TITLE
texture glitch in 1.28

### ISSUE THREAD

**Issue by PONYMODZ** [Sildurs-shaders/sildurs-shaders.github.io#63]
beds, chests, and signs render incorrectly in optifine 1.16.1 pre9 with v1.28 Extreme-VL
![2020-07-24_12 46 47](https://user-images.githubusercontent.com/31258183/88384548-e8ade180-cdac-11ea-9377-c5cbe6581b56.png)

**Comment by Sildurs-shaders** [comment]
Optifine preview issues with bump and parallax mapping enabled. A workaround might be possible to be implemented but this should be fixed by optifine eventually.

**Comment by Sildurs-shaders** [comment]
Implemented a workaround in the upcoming update.
