### ISSUE TITLE
Transparency Bug with Extreme v1.28

### ISSUE THREAD

**Issue by agarian-2** [Sildurs-shaders/sildurs-shaders.github.io#67]
I'm unsure if this is where I am supposed to report bugs with the shader, but I've noticed that with stained glass, looking at the sky through it causes strange bugs. Most of the time it causes the sky to be straight-black, but sometimes weird flashing colors occur. And it only affects the sky; all blocks behind the glass render like normal.
![2020-07-30_19 03 55](https://user-images.githubusercontent.com/36286279/88982898-7f8c0980-d297-11ea-96d1-064205c8bc69.png)
![2020-07-30_19 03 52](https://user-images.githubusercontent.com/36286279/88982899-8024a000-d297-11ea-9e43-735f8e6c6914.png)
The above screenshots show how the sky looks while looking through a box of cyan stained glass (there is no solid wall). It also happens in Volumetric Lighting v1.28, but I have not tested the other versions such as High, Medium, etc.

**UPDATE:** This doesn't seem to happen in 1.16. It does in 1.8 and 1.12, however.

**Comment by Sildurs-shaders** [comment]
Sounds like optifine issues then, does it work fine on 1.14.4? Thats the latest stable version.

**Comment by agarian-2** [comment]
It does not work there either; the transparency glitching still occurs. It only works fine in 1.16.x. Has there been any sort of color blending changes between 1.14 and 1.16? That's my only guess as to what causes the bug.

**Comment by Sildurs-shaders** [comment]
Hmm, maybe you should forward this to the optifine github instead.

**Comment by agarian-2** [comment]
But that doesn't explain why versions 1.27- work on all Minecraft versions just fine. It's only 1.28 that has this issue, which is when reflections were reworked.

**Comment by Sildurs-shaders** [comment]
Closed for now, might be fixed in upcoming update.

**Comment by agarian-2** [comment]
Can confirm the fix has worked (only took me a month to figure that out lol).
