### ISSUE TITLE
Water blinking through non-transparent blocks

### ISSUE THREAD

**Issue by Jiranikan** [Sildurs-shaders/sildurs-shaders.github.io#68]
Playing on custom vanila server and realized i should update my Sildurs vibrant from 1.27 to 1.28. I'm using "high" version and these blinking textures of water didn't appear in previous versions.
Used in: VERSION 1.16.1, FORGE 32.0.93, MODS = OptiFine-1.16.1_HD_U_G2_pre10, tl_skin_cape_forge_1.16.1-1.12

Here's a screenshot of what it looks like:
![2020-07-31_16 42 03](https://user-images.githubusercontent.com/69046834/89046239-f8996880-d34c-11ea-8b2a-dd18b0c667ee.png)

I would appreciate any help on fixing this.
Edit: Nicknames above other players seem to be blacked out too

**Comment by Mace68** [comment]
> Edit: Nicknames above other players seem to be blacked out too

I'm also having a similar issue with text above entities being black through non-transparent blocks that only happens on 1.28.

![Blacked out text](https://imgur.com/84QfBhO.png)

**Comment by Sildurs-shaders** [comment]
What's your gpu? Try updating its drivers. Also check if it happens on 1.14.4. (the water issue)

**Comment by Jiranikan** [comment]
My GPU is Radeon RX 560 series but my drivers are up to date. Didn't stop me from re-installing them.
After Mace68's reply i noticed i had outdated optifine for some reason, my launcher usually auto-updates optifine.

After drivers re-install and optifine update, i can no longer replicate the water issue. Seems like optifine was the villain. Thanks for the help though i really appreciate it!

**Comment by Sildurs-shaders** [comment]
Sounds like an optifine issue then, you should forward this to the optifine github.

**Comment by Jiranikan** [comment]
OK! Thanks for pinpointing the source of this issue, orwarded to optifine github for now.

**Comment by Sildurs-shaders** [comment]
Closed since this is an optifine issue.
