### ISSUE TITLE
Overlays seem to not be rendering lighting properly.

### ISSUE THREAD

**Issue by Mace68** [Sildurs-shaders/sildurs-shaders.github.io#69]
Overlays seem to not be rendering lighting properly. This happens in both 1.27 and 1.28.
![Screen Shot](https://i.imgur.com/ek96sjg.jpg)

[Edit]
I've tried on all versions of OptiFine up to and including OptiFine 1.16.1 HD U G2. I tested other shader packs and didn't see the issue. I do still prefer this pack though so I have disabled connected textures for the time being.

**Comment by Sildurs-shaders** [comment]
Does it work in 1.14.4?

**Comment by Mace68** [comment]
> Does it work in 1.14.4?

It looks the same in 1.14.4 (OptiFine_1.14.4_HD_U_F5)

**Comment by Sildurs-shaders** [comment]
What's your gpu and can you link me the resourcepack for testing. Also make sure your gpu drivers are up to date.

**Comment by Mace68** [comment]
- GPU is the GTX 1660 Ti
- Official nVidia Linux driver v440.100 on KDE Neon, which is basically Ubuntu LTS (18.04 at the moment) with an always updated KDE Plasma installation.
- Latest default Minecraft Java launcher.
- Resource pack is v4.1 here: https://www.curseforge.com/minecraft/texture-packs/lb-photo-realism-reload

Let me know if you need anything else, thanks for looking into this.

**Comment by Sildurs-shaders** [comment]
Okay so the issue with this is that due to the translucent property set in the resourcepack these textures are rendered in gbuffers_water for shaders. Which is kinda bad. One way to fix it is by changing the properties in the resourcepack to something else.
