### ISSUE TITLE
Stop rendering shader when pause menu is shown

### ISSUE THREAD

**Issue by XXXBold** [Sildurs-shaders/sildurs-shaders.github.io#70]
If the pause menu is shown, rendering of the shader should also be paused, like the game and it's animations itself. This would save a lot of ressources when pausing the game for a longer time (Only applies to singleplayer, in multiplayer the animations ofc will continue).

I use the most recent 1.28 version, with minecraft 1.14.4 on Linux Mint 19.3 with an AMD card (driver: mesa 20.2-dev) (Just in case this is related to my system somehow).

**Comment by douira** [comment]
Not an expert, but I believe that shader doesn't control this but rather Optifine does.

**Comment by Sildurs-shaders** [comment]
Suggest this on the optifine github instead.
https://github.com/sp614x/optifine/issues
