### ISSUE TITLE
No Biome Blending for Nether Biomes

### ISSUE THREAD

**Issue by maikotui** [Sildurs-shaders/sildurs-shaders.github.io#72]
I am using Shildurs Shaders v1.28 (Extreme and Extreme-VL) on Optifine HD G2 Ultra. When in the nether, I get no blending between biomes despite having biome blending enabled under "Video Settings" -> "Details" -> "Biome Blending set to 5x5". When no shaders are active ("Video settings" -> "Shaders" -> "Off"), biome blending works as intended. Once I switch to Shildurs Shaders 1.28 Extreme or Shildurs Shaders 1.28 Extreme-VL, biome blending no longer works.
Here are two screenshots from two positions, one block away from each other. 

![2020-08-02_20 03 30](https://user-images.githubusercontent.com/32694968/89140641-6e453600-d4ff-11ea-91bb-c7f3cf9bd364.png)
![2020-08-02_20 03 33](https://user-images.githubusercontent.com/32694968/89140648-70a79000-d4ff-11ea-9c1e-1c8960d2bac0.png)

I am on Minecraft 1.16.1 with an RTX 2070. I am running OpenGL V. 4.6.0 and Nvidia 451.67.

**Comment by maikotui** [comment]
Developer is aware of the problem, it was mentioned in the changelog for v1.28 that "The blend between basalt biome and other biomes is not as smooth." For now I will keep this issue open as there are no other issues tracking this problem.

**Comment by Sildurs-shaders** [comment]
Fixed in the upcoming update.
