### ISSUE TITLE
banner texture issue (1.28)

### ISSUE THREAD

**Issue by 11thenun** [Sildurs-shaders/sildurs-shaders.github.io#73]
Banners are displayed differently with shaders (see picture). But with Optifine and without shaders they are displayed normally.
![2020-08-03_14 35 49](https://user-images.githubusercontent.com/69152119/89183784-0db60780-d598-11ea-8165-4ccaedd47586.png)

**Comment by 11thenun** [comment]
(It's on the newest Optifine version -> OptiFine 1.16.1 HD U G2)

**Comment by Sildurs-shaders** [comment]
Does this happen on 1.14.4

**Comment by 11thenun** [comment]
I don't know. It happens since the latest version of the shaders. With version 1.27 of the shaders they were displayed normally.

**Comment by Sildurs-shaders** [comment]
Fixed in upcoming update
