### ISSUE TITLE
Object border color bug

### ISSUE THREAD

**Issue by XXXBold** [Sildurs-shaders/sildurs-shaders.github.io#74]
I've found a very annoying bug regarding the border color of some objects, most noteable if they're at distance, but also happens sometimes if close. It's a bit hard to explain in textform, so I'll add screenshots to clarify.
When looking in the distance (Renderdistance is set to 16 Chunks), the border of the almost viewable terrain is colored the same color as what the player is currently looking at. This is very visible in the dark with e.g. a torch:
![2020-08-03_10 24 23](https://user-images.githubusercontent.com/30773753/89219930-381bbb00-d5c0-11ea-8ef4-e851ac50838d.png)
When not looking at the torch anymore, the border color also changes:
![2020-08-03_10 24 29](https://user-images.githubusercontent.com/30773753/89219989-55e92000-d5c0-11ea-9123-33f2ca87ce31.png)

Most of the time this only happens over such far distances, but it can also happen in other scenarions, see next screenshot (The water source).
![2020-08-03_21 02 18](https://user-images.githubusercontent.com/30773753/89220559-546c2780-d5c1-11ea-8cea-bd43a91b7a27.png)
![2020-08-03_21 02 32](https://user-images.githubusercontent.com/30773753/89220565-56ce8180-d5c1-11ea-8347-b026cf8c2b45.png)

**Reproduce**
Scenario 1 is easy to reproduce: Place a torch when it's night, focus it with the cursor and see the distant terrain.

**Shader**
Sildur Shader 1.28 Extreme VL

**Minecraft Details**
Version 1.16.1, but others (for example, 1.14.2) are also affected

**System**
```
System:    Host: Simons-PC Kernel: 5.4.0-42-generic x86_64 bits: 64 compiler: gcc v: 7.5.0 Desktop: Cinnamon 4.4.8 
           Distro: Linux Mint 19.3 Tricia base: Ubuntu 18.04 bionic 
Machine:   Type: Desktop System: Gigabyte product: X570 AORUS ELITE v: -CF serial: <filter> 
           Mobo: Gigabyte model: X570 AORUS ELITE v: x.x serial: <filter> UEFI: American Megatrends v: F20 date: 07/07/2020 
CPU:       Topology: 12-Core model: AMD Ryzen 9 3900X bits: 64 type: MT MCP arch: Zen L2 cache: 6144 KiB 
           flags: lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm bogomips: 182055 
           Speed: 2225 MHz min/max: 2200/3800 MHz Core speeds (MHz): 1: 2196 2: 2196 3: 2191 4: 2192 5: 2196 6: 2200 7: 2194 
           8: 2195 9: 2195 10: 2196 11: 2196 12: 2196 13: 2195 14: 2195 15: 2193 16: 2192 17: 2189 18: 2196 19: 2196 20: 2196 
           21: 2196 22: 2196 23: 2196 24: 2195 
Graphics:  Device-1: Advanced Micro Devices [AMD/ATI] vendor: Sapphire Limited driver: amdgpu v: kernel bus ID: 0c:00.0 
           Display: x11 server: X.Org 1.20.8 driver: amdgpu,ati unloaded: fbdev,modesetting,radeon,vesa 
           resolution: 1920x1080~60Hz, 1920x1080~60Hz, 1920x1080~50Hz 
           OpenGL: renderer: AMD Radeon RX 5700 XT (NAVI10 DRM 3.35.0 5.4.0-42-generic LLVM 10.0.1) 
           v: 4.6 Mesa 20.2.0-devel (git-c147604 2020-08-02 bionic-oibaf-ppa) direct render: Yes 
Audio:     Device-1: C-Media CMI8788 [Oxygen HD Audio] vendor: ASUSTeK Virtuoso 100 driver: snd_virtuoso v: kernel 
           bus ID: 06:04.0 
           Device-2: Advanced Micro Devices [AMD/ATI] driver: snd_hda_intel v: kernel bus ID: 0c:00.1 
           Device-3: Advanced Micro Devices [AMD] vendor: Gigabyte driver: snd_hda_intel v: kernel bus ID: 0e:00.4 
           Sound Server: ALSA v: k5.4.0-42-generic 
Network:   Device-1: Intel I211 Gigabit Network vendor: Gigabyte driver: igb v: 5.6.0-k port: e000 bus ID: 04:00.0 
           IF: enp4s0 state: up speed: 1000 Mbps duplex: full mac: <filter> 
           IF-ID-1: tun0 state: unknown speed: 10 Mbps duplex: full mac: N/A 
           IF-ID-2: virbr0 state: down mac: <filter> 
           IF-ID-3: virbr0-nic state: down mac: <filter> 
Drives:    Local Storage: total: 6.33 TiB used: 1.44 TiB (22.8%) 
           ID-1: /dev/nvme0n1 vendor: Corsair model: Force MP510 size: 894.25 GiB 
           ID-2: /dev/sda vendor: Crucial model: CT2000MX500SSD1 size: 1.82 TiB 
           ID-3: /dev/sdb vendor: Western Digital model: WD40EZRZ-00GXCB0 size: 3.64 TiB 
Partition: ID-1: / size: 878.70 GiB used: 220.67 GiB (25.1%) fs: ext4 dev: /dev/nvme0n1p2 
Sensors:   System Temperatures: cpu: 57.0 C mobo: N/A 
Use of uninitialized value $val2 in string eq at /usr/bin/inxi line 5759.
Use of uninitialized value $val2 in split at /usr/bin/inxi line 5764.
Use of uninitialized value $val2 in concatenation (.) or string at /usr/bin/inxi line 5766.
Use of uninitialized value $val2 in concatenation (.) or string at /usr/bin/inxi line 5767.
Use of uninitialized value $val2 in concatenation (.) or string at /usr/bin/inxi line 5768.
           Fan Speeds (RPM): N/A gpu: fan: 889 
Info:      Processes: 439 Uptime: 11h 45m Memory: 31.37 GiB used: 9.82 GiB (31.3%) Init: systemd runlevel: 5 Compilers: 
           gcc: 7.5.0 Shell: bash v: 4.4.20 inxi: 3.0.32
```

**Comment by Sildurs-shaders** [comment]
Wow this one's an old driver bug, are there newer or different drivers available for your RX 5700 XT?

**Comment by XXXBold** [comment]
Hm, I'm using the most recent opensource drivers (mesa 20.2-dev) from this PPA: https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers

Are there any options (Environment variables, ...) which could cause the bug? If you need more information, just tell me and I'll do what I can :)

**Comment by Sildurs-shaders** [comment]
Hmm, there's not much you can do about it I don't think.

**Comment by Sildurs-shaders** [comment]
Might be fixed in the upcoming update

**Comment by Sildurs-shaders** [comment]
Closed for now, reply if it's still not fixed in the upcoming update.

**Comment by Sildurs-shaders** [comment]
Nevermind, after more testing a similar bug occurs on an intel hd 4600 running on linux kubuntu. Disabling sky blur in the sky and lighting section fixes it, does this also work for you?

**Comment by Sildurs-shaders** [comment]
Was able to reproduce your issue on a Radeon HD 8730M Mesa driver 20.3 from oibaf PPA.
Fixed in upcoming update, sky blur will also blur distance on linux system, thats the same workaround used for amd cards.
