### ISSUE TITLE
Shadow automatically turning off

### ISSUE THREAD

**Issue by weebykun** [Sildurs-shaders/sildurs-shaders.github.io#75]
Was working fine for 3 days until now, no changes in versions or software.
Minecraft 1.16.1
Optifine 1.16.1 HD U G2
Sildur's Vibrant shaders v1.28 High

Turning shadows off and back on will bring them back but will go away after moving a few blocks. Issue seems to occur in all shader presets. Reinstall of shader and optifine did not fix issue. Please let me know if you need any other information.

![Shadows](https://user-images.githubusercontent.com/69225431/89360543-6667cc00-d68e-11ea-86c4-75191e768c3f.png)
![No Shadows](https://user-images.githubusercontent.com/69225431/89360550-69fb5300-d68e-11ea-844b-8193234d82b2.png)

**Comment by Sildurs-shaders** [comment]
Optifine issues, try deleting the soul campfire id in block.properties, that might fixes it for some reason.

**Comment by weebykun** [comment]
My apologies but where would I find that?

**Comment by Sildurs-shaders** [comment]
In the shaderpack zip file, edit block.properties with an editor, like notepad++ or visual studio code.

**Comment by weebykun** [comment]
Is it the one that says "soul_campfire: lit=true"?

**Comment by Sildurs-shaders** [comment]
Yep, did that do the trick for you?

**Comment by weebykun** [comment]
Afraid it did not :(

**Comment by Sildurs-shaders** [comment]
Try removing the normal campfire id aswell.

**Comment by Sildurs-shaders** [comment]
Should be fixed in upcoming update, added a workaround for this optifine bug. Thanks to fayer3

**Comment by weebykun** [comment]
Hey Sildur I'm still having trouble with this issue. It was fixed for a bit and today I streamed my world on discord and it started happening again. Not sure if this is the cause but its when it started again. Tried removing optifine and reinstalling shaders, still no luck. Sucks I really love your work man.
