### ISSUE TITLE
Error: Invalid program "composite1" with v1.28

### ISSUE THREAD

**Issue by XSoussou** [Sildurs-shaders/sildurs-shaders.github.io#76]
So basically, whenever I'm in the end dimension I get this error and the screen is completely black.
I use the 1.28 Extreme-Volumetric version :)

> [Shaders] Error linking program: 21 (composite1)
> [Shaders] Info log: composite1
> Fragment info
> \-------------
> 0(178) : error C0000: syntax error, unexpected reserved word "if" at token "if"
> 0(180) : error C1503: undefined variable "normal"
> 0(182) : error C1503: undefined variable "normal"
> 0(182) : error C1503: undefined variable "normal"
> 0(183) : error C1503: undefined variable "normal"
> 0(183) : error C1503: undefined variable "normal"
> 0(188) : error C0000: syntax error, unexpected reserved word "if" at token "if"
> 0(207) : error C1503: undefined variable "trp"
> 0(209) : error C0000: syntax error, unexpected '=', expecting "::" at token "="
> 0(215) : error C1503: undefined variable "reflectedVector"
> 0(215) : error C1503: undefined variable "normalfragpos1"
> 0(217) : error C1503: undefined variable "normalfragpos1"
> 0(222) : error C0000: syntax error, unexpected '=', expecting "::" at token "="
> 0(226) : error C1503: undefined variable "fragpos0"
> 0(226) : error C1503: undefined variable "reflectedVector"
> 0(231) : error C0000: syntax error, unexpected '.', expecting "::" at token "."
> 0(248) : error C0000: syntax error, unexpected reserved word "if" at token "if"
> (0) : error C2003: incompatible options for link

**Comment by Sildurs-shaders** [comment]
Fixed in upcoming update.
