### ISSUE TITLE
Fog in nether

### ISSUE THREAD

**Issue by VozikCZE** [Sildurs-shaders/sildurs-shaders.github.io#77]
Hi, there is no fog in nether, which isnt good in custom world.

![image](https://user-images.githubusercontent.com/48393384/90150509-08ba3a80-dd86-11ea-9cdf-465a991619ec.png)
![image](https://user-images.githubusercontent.com/48393384/90150598-2091be80-dd86-11ea-9f2e-70488fd460af.png)

**Comment by Sildurs-shaders** [comment]
What dimension is that? There's is fog in the nether, if this is a custom dimension it will load the overworld shaders though. Copy the world-1 folder in the shaderpack zip file and name it to ur custom dimension id.

**Comment by Sildurs-shaders** [comment]
Optifine bug, closed for now.
