### ISSUE TITLE
mysterious crash while upgrading from 1.22 to 1.28 (1.12.2)

### ISSUE THREAD

**Issue by MozarteanChaos** [Sildurs-shaders/sildurs-shaders.github.io#78]
as the title says. i use sildur's shaders (vibrant, medium). when using 1.22 and trying to change to 1.28, my game crashes. this occurs regardless of whether i do this in the main menu or while in a world. lite has this problem too, although the log file was retrieved while using medium.
i don't know how to read the crash log, so i'm not entirely sure if it's this mod's fault... if it isn't, any information on which mod might be causing it and/or how to get around it would be much appreciated, but i understand if that's not possible.
crash log:
https://pastebin.com/X5ix9e4h

thank you for your time, regardless of whether or not it's something you can fix

(some additional information: switching from medium 1.22 to high 1.22 or back _does not_ cause a crash. switching from medium 1.22 to enhanced default 1.11 _does not_ cause a crash. it's too late in the day for me to test other versions right now)

**Comment by jagyCZ** [comment]
Unfortunately i have the same issue, few seconds after i click at your shader the game crashes. Somethings bad with the 1.28
game ver.: 1.12.2
optifine: 1.12.2_HD_U_F5
crashlog: https://dl.dropboxusercontent.com/s/awu1ehyqf2yy7uu/crash-2020-08-17_19.01.42-client.txt

**Comment by Sildurs-shaders** [comment]
You must use optifine preview version F6 for 1.12.2. This crash is an optifine bug that was fixed in the preview version.
