### ISSUE TITLE
Weird leaf x-ray bug

### ISSUE THREAD

**Issue by Rubenzoom** [Sildurs-shaders/sildurs-shaders.github.io#79]
Theres a weird leaf bug where leafs become see through and become x-rays, not sure if thats a good explanation but here are some screenshots so its clearer:

![2020-08-07_12 11 39](https://user-images.githubusercontent.com/67695681/90525037-151c0a00-e16f-11ea-9d5d-74cabf57b28f.png)
![2020-08-14_19 42 35](https://user-images.githubusercontent.com/67695681/90525041-164d3700-e16f-11ea-98bc-93df55bdbc31.png)
![2020-08-14_20 03 15](https://user-images.githubusercontent.com/67695681/90525044-164d3700-e16f-11ea-81e9-0899cd410fe0.png)
![2020-08-07_12 11 34](https://user-images.githubusercontent.com/67695681/90525045-16e5cd80-e16f-11ea-8f00-551d909af66c.png)

I tried this on the Hypixel server on 1.8.9, also seen this on 1.16.1, im guessing this happens on all versions

**Comment by Sildurs-shaders** [comment]
This shouldn't happen if leaves are set to fancy.

**Comment by Sildurs-shaders** [comment]
Closed for now, feel free to reply.
