### ISSUE TITLE
Water and stained glass color bug

### ISSUE THREAD

**Issue by Rubenzoom** [Sildurs-shaders/sildurs-shaders.github.io#80]
When going into the water and looking up while moving the camera around, the sky would be switching colors really quickly, same goes with stained glass when moving the camera. It's a bit annoying, but it could also be dangerous if somebody has epilepsy. 

One time I tried to screenshot it on 1.16.1 but it didnt happen, I thought it got patched but while playing on a server it happened again with some stained glass. So maybe it just happens sometimes and sometimes not.

**Comment by Sildurs-shaders** [comment]
Should be fixed in the upcoming update.
