### ISSUE TITLE
Parallax distorts textures on non-rectangular faces

### ISSUE THREAD

**Issue by wchen1990** [Sildurs-shaders/sildurs-shaders.github.io#81]
[At first I thought this might have been an issue with the mod I was using](https://github.com/ShetiPhian/Localizations-and-Issues/issues/248#issuecomment-676755700) and even though I think the mod's obj models should try to cut down on the number of triangle faces after testing out various shaders with Parallax options, I found that most of the shaders have the same issue [except one](https://www.curseforge.com/minecraft/customization/beyond-belief-shaders).

The linked issue should have plenty of screenshots showing off the issue with regards to non-rectangular faces.

Let me know if you need any more info.

**Comment by Sildurs-shaders** [comment]
Does this still happen in v1.281?

**Comment by wchen1990** [comment]
Yea it still happens on v1.281.

Here are two images showing the issue still happening in v1.281:
https://i.imgur.com/OV8cn80.png
https://i.imgur.com/AdDm4yQ.png

**Comment by Sildurs-shaders** [comment]
Might be fixed in newer versions, comment again if not.

**Comment by wchen1990** [comment]
Can confirm that this is no longer and issue with at least v1.32.

Thanks for the help on such a niche matter.
