### ISSUE TITLE
Cannot disable shadows on SVS 1.28

### ISSUE THREAD

**Issue by partyp770** [Sildurs-shaders/sildurs-shaders.github.io#82]
Disabling shaders on the latest version of Sildur's Vibrant Shaders, any variant, breaks gbuffers_water.
Running:
Optifine HD G1_pre30 Ultra (1.15.2)
Sildur's Vibrant Shaders 1.28

Hardware:
GPU: RX 570
CPU: Ryzen 5 2600

How to reproduce:
Reset all settings to default in SVS 1.28
Set "Shadows" to off within the "Shadows..." menu.

**Comment by Sildurs-shaders** [comment]
Thanks for the report, fixed in upcoming update.

**Comment by partyp770** [comment]
Thank you so much!
