### ISSUE TITLE
(Sildur's vibrant shaders lite) Invisibility glitch

### ISSUE THREAD

**Issue by Rubenzoom** [Sildurs-shaders/sildurs-shaders.github.io#83]
I was playing in hypixel 1.8.9 and played tnt run, when i died i could spectate saw a guy that seemed to be afk that was dead and invisible and we i looked at him his skin seemed inside out and some parts would be completely erased with the background

Here are some screenshots of me with invisibility:
![2020-08-24_18 30 53](https://user-images.githubusercontent.com/67695681/91071223-3893f880-e638-11ea-93c5-505369d992f0.png)
![2020-08-24_18 30 40](https://user-images.githubusercontent.com/67695681/91071230-39c52580-e638-11ea-9fe2-f34f61295cf1.png)

**Comment by Sildurs-shaders** [comment]
Optifine issue
