### ISSUE TITLE
(Sildur's enhanced default) Shadow lines on blocks

### ISSUE THREAD

**Issue by Rubenzoom** [Sildurs-shaders/sildurs-shaders.github.io#84]
Well it's just that, lines on blocks. I think it just happens when i change the shader's settings, but im not sure.

Here are some screenshots:
![2020-08-24_18 39 16](https://user-images.githubusercontent.com/67695681/91072197-6ded1600-e639-11ea-9272-88d882b299d2.png)
Doesnt appear to happen on blocks with shadows
![2020-08-24_18 38 55](https://user-images.githubusercontent.com/67695681/91072374-b4427500-e639-11ea-97e1-3544b14db694.png)

**Comment by Sildurs-shaders** [comment]
Looks like u messed with the shadow settings, this is shadows acne. Reset your settings.

**Comment by noob2468024680** [comment]
not workig

**Comment by noob2468024680** [comment]
it is already in defalt
