### ISSUE TITLE
Feature Request: When holding a torch emit light

### ISSUE THREAD

**Issue by acheronfail** [Sildurs-shaders/sildurs-shaders.github.io#86]
I've seen some other shader packs (not as good as this one IMO) that emit light when you're holding a torch.
This is really useful (for example, when digging a long tunnel you can just hold a torch and always see what you're digging) and to me it's the only thing missing from this excellent shader pack.

To be clear:

When holding a torch (in either hand) have it emit light.

---

Thanks again for this shader pack!

**Comment by Sildurs-shaders** [comment]
I removed that feature a long time ago since optifine provides it's own. In video settings enable dynamic lights and set it to fancy.

**Comment by acheronfail** [comment]
I did not know that, thanks!
