### ISSUE TITLE
Charged creeper is not animated

### ISSUE THREAD

**Issue by PQCraft** [Sildurs-shaders/sildurs-shaders.github.io#87]
I have OCD, so I can't stand this (enough that i'm making a bug report). The charged creeper doesn't work in any of the 1.28 builds. IDK how to fix it. So I made a bug report
Screenshot:
![2020-08-30_18 36 27](https://user-images.githubusercontent.com/58464017/91670900-c582fa00-eaef-11ea-80a9-bcffbbd034ee.png)

**Comment by PQCraft** [comment]
I didn't mention, but the lighting for tnt, creepers, and lighting doesn't work (1.12.2).

**Comment by Sildurs-shaders** [comment]
Fixed in upcoming version.
