### ISSUE TITLE
Texture alpha transparency not working in 1.28

### ISSUE THREAD

**Issue by SafiraSan** [Sildurs-shaders/sildurs-shaders.github.io#88]
I am using the 1.28 (Extreme) shader pack and noticed that the alpha transparency on the horse marking textures does not work in 1.28. In 1.27 Extreme and Extreme-VL, the transparency works as expected.
![2020-09-06_13 23 14](https://user-images.githubusercontent.com/39302898/92325787-1e4d1800-f045-11ea-9805-0c0fca1ad476.png)
Version 1.27
![2020-09-06_13 23 23](https://user-images.githubusercontent.com/39302898/92325793-29a04380-f045-11ea-8e37-afbcd0b8f380.png)
Version 1.28

I am using Minecraft 1.16.2 with OptiFine 1.16.2 HD_U_G3. Texture transparency works with OptiFine but without shaders.

Graphics: NVIDIA GTX1070 6GB

Thank you for all your amazing work on these fantastic shaders, Sildur.

**Comment by EnterOriginal** [comment]
Bit random question, but what texture pack are you using? :)

**Comment by SafiraSan** [comment]
Hi! No worries; it's [Chroma Hills](https://www.chromahills.com/), by the amazing Syclone.

**Comment by Sildurs-shaders** [comment]
Should be fixed in upcoming update.

**Comment by SafiraSan** [comment]
> Should be fixed in upcoming update.

Fantastic. Thanks so much for all your work, Sildur.
