### ISSUE TITLE
Add information on JAVA Vs Bedrock. 

### ISSUE THREAD

**Issue by mesqueeb** [Sildurs-shaders/sildurs-shaders.github.io#9]
Hi! 
I assume this is only for the JAVA edition?  
Maybe it can be good to write that in the readme and on the website as well. ;)

**Comment by Sildurs-shaders** [comment]
Since it requires optifine as listed in the installation guide aswell as the supportive minecraft versions (1.7.10 - 1.14.4) it should be rather clear that this is only for the java edition.
