### ISSUE TITLE
Light is messed up even on default settings

### ISSUE THREAD

**Issue by oofnames** [Sildurs-shaders/sildurs-shaders.github.io#90]
![Annotation 2020-09-11 151922](https://user-images.githubusercontent.com/60379676/92924832-37d5d180-f442-11ea-8c27-f1d850ed6d11.png)
![2020-09-10_15 17 21](https://user-images.githubusercontent.com/60379676/92728069-ce3dc080-f378-11ea-8bf5-423adc9fbd59.png)

Picture above

I only have optifine installed and it doesnt work
Here are the config files
[optionsof.txt](https://github.com/Sildurs-shaders/sildurs-shaders.github.io/files/5201530/optionsof.txt)
[optionsshaders.txt](https://github.com/Sildurs-shaders/sildurs-shaders.github.io/files/5201531/optionsshaders.txt)
[options.txt](https://github.com/Sildurs-shaders/sildurs-shaders.github.io/files/5201532/options.txt)

It just suddenly stopped working. 
I have an 1060 6gb i7 4790 and 16gb of ram
If  you need more info comment what you need

**Comment by Sildurs-shaders** [comment]
Optifine / driver issue.
