### ISSUE TITLE
CC tweaked/journey maps rendering bug

### ISSUE THREAD

**Issue by josh-65** [Sildurs-shaders/sildurs-shaders.github.io#91]
Don't know if this is fixable but CC tweaked has this ghost effect and is bright white on the monitors and Journeymap waypoints are transparent in general and not visible in caves or dark buildings.

![2020-09-25_15 59 58](https://user-images.githubusercontent.com/26977075/94282934-519a0d00-ff48-11ea-9892-ad22d63af76b.png)
![2020-09-25_15 51 48](https://user-images.githubusercontent.com/26977075/94282923-4f37b300-ff48-11ea-8760-c07f29850de4.png)

**Comment by Sildurs-shaders** [comment]
Can't do much about mod support, might be fixed in upcoming update though.
