### ISSUE TITLE
Breaking animation not blending alpha

### ISSUE THREAD

**Issue by Mattmathics** [Sildurs-shaders/sildurs-shaders.github.io#92]
The breaking animation does not blend the alpha correctly. The pixels where there is no color is rendering properly but the other pixels are displayed with full alpha.
![breaking animation](https://user-images.githubusercontent.com/43424482/94351451-95634400-0026-11eb-97d0-6952bf9b0a7d.png)
Shaders (left) vs. just OptiFine (right)

I went and checked an older version of OptiFine (1.14.4) as well and the same breaking animation bug is present when using the newest version of the shaders.

**Comment by sylviev4x** [comment]
I'm getting this glitch too! But it fixes when you download the version 1.27 of Sildurs Shaders. Look for "Previous Versions:" and find v1.27

https://sildurs-shaders.github.io/downloads/

I hope this helps you

**Comment by Mattmathics** [comment]
Thanks so much!

- Matt McFarlane

**Comment by Sildurs-shaders** [comment]
Fixed in upcoming release.
