### ISSUE TITLE
Hey sildur...

### ISSUE THREAD

**Issue by ronaldvp1108** [Sildurs-shaders/sildurs-shaders.github.io#93]
There is a problem when you enable motionblur... Depth of field doesnt work anymore, can you fix this problem? Please and thank you!
![Bug2](https://user-images.githubusercontent.com/71985266/94373020-fc850500-00c7-11eb-98b3-e5713c2c2b52.png)

I have both motionblur and Depth of field.

**Comment by Sildurs-shaders** [comment]
This is intended and the option note says so aswell, only one at a time is supported.
