### ISSUE TITLE
Nether is dark unless you enable the Shaders in the Overworld 1st.

### ISSUE THREAD

**Issue by dragon3025** [Sildurs-shaders/sildurs-shaders.github.io#94]
Even light sources like Sea Lanterns show up as dark silhouettes. Being in the Overworld then entering the Nether fixes it. I found a reddit post where others where having the same problem: https://www.reddit.com/r/Optifine/comments/hz1toq/sildurs_vibrant_shaders_v128_breaks_in_the_nether/

**Comment by Sildurs-shaders** [comment]
Optifine issue, might be fixed in newer optifine versions.
