### ISSUE TITLE
Missing textures in 1.6.3

### ISSUE THREAD

**Issue by nevis2us** [Sildurs-shaders/sildurs-shaders.github.io#95]
Textures are missing for the spruce trapdoor in 1.6.3 if Sildur's Vibrant Shaders is the default when the game starts:

[Missing textures](https://ipros24.ru/2020-09-28_13-21-28/)

An simple workaround is to turn shaders OFF in Video Settings and then select the Vibrant Shaders again but it has to be repeated each time I restart Minecraft:

[Fixed](https://ipros24.ru/2020-09-28_13-22-13/)

**My configuration:**

Minecraft: 1.6.3
Forge: 1.16.3-forge-34.1.0
OptiFine: 1.16.3 HD U G3
Sildur's Vibrant Shaders: v1.281 Extreme

OpenGL Version: 4.6.0 NVIDIA 450.66
Renderer: GeForce GTX 650/PCIe/SSE2

Let me know if you need more info.
Thanks.

**Comment by Sildurs-shaders** [comment]
Optifine issue.
