### ISSUE TITLE
Spectral arrows don't give off a glowing outline when it hits a mob

### ISSUE THREAD

**Issue by Shtuffs** [Sildurs-shaders/sildurs-shaders.github.io#96]
Spectral arrows seem to only give off the potion effect, but not the actual glow outline: 

![image](https://user-images.githubusercontent.com/46979803/94488597-e606a880-01b0-11eb-9f4e-1a3557bbf55e.png)

I'm running sildur's vibrant shaders on minecraft 1.16.1. I know it's a shader issue because it gives off the correct glow outline when I have them off: 

![image](https://user-images.githubusercontent.com/46979803/94488679-0a628500-01b1-11eb-804b-1b0289b8e1d7.png)

**Comment by Sildurs-shaders** [comment]
Spectral arrows are currently not supported.

**Comment by ITCMD** [comment]
All glowing does not work at the moment. Big issue for arcade games and certain mods.

**Comment by ITCMD** [comment]
Looks like Complimentary Shaders found a workaround, might be worth looking into https://github.com/sp614x/optifine/issues/3662

**Comment by Sildurs-shaders** [comment]
Fixed in upcoming release (at least of overworld)
