### ISSUE TITLE
The furnace shook like leaves

### ISSUE THREAD

**Issue by 30266-Official** [Sildurs-shaders/sildurs-shaders.github.io#98]
![2020-10-03 09-18-02](https://user-images.githubusercontent.com/63724619/94980211-186e2800-055a-11eb-82fd-903ef1c5794c.gif)

**Comment by 30266-Official** [comment]
For 1.281;1.16.3

**Comment by Sildurs-shaders** [comment]
Make sure optifine is up to date, might be an optifine / mod issue.
